project: 
  type: book

  preview: 
    browser: false
    port: 3000

book:
  title: "Apuntes Historia de España para la PAU"
  description: "Apuntes de Historia de España para preparar la PAU: temas clave, resúmenes, definiciones y conceptos esenciales explicados de forma clara."
  page-footer: © Copyright 2025
  subtitle: "Prueba de Acceso Universidad Comunidad Valenciana"
  language: es
  bread-crumbs: false
  sidebar: 
    title: "Historia de España  PAU CV"
    collapse-level: 1
    border: true
    
  image: pictures/Portada.png
    
  cover-image: pictures/Portada.png
  
  favicon: pictures/Portada.png
  chapters: 
    - href: index.qmd
      text: Introducción
    - part: "Siglo XIX"
      chapters:
      - pages/Unidades/Fernando.qmd
      - pages/Unidades/MCristina.qmd
      - pages/Unidades/Industria.qmd
      - pages/Unidades/Sociedad-XIX.qmd
      - pages/Unidades/Inicio-Restauracion.qmd 

    - part: "Siglo XX" 
      chapters:
      - pages/Unidades/Fin-Restauracion.qmd
      - pages/Unidades/Sociedad-XX.qmd
      - pages/Unidades/Republica2.qmd
      - pages/Unidades/Guerra-Civil.qmd
      - pages/Unidades/Franquismo.qmd
      - pages/Unidades/Franquismo-2.qmd
      - pages/Unidades/Transicion.qmd

    - pages/Vocabulario-s-xix.qmd
    
 
  
format:
  html:
    smooth-scroll: true
    include-in-header: "adsense-head.html"
    social-share: true
    toc-depth: 4
    language: 
      title-block-author-single: "Autor"
      title-block-published: "Año de publicación"
      toc-title-website: "Índice"
      toc-title-document: "Índice"
    theme: 
      light: [cosmo, styles/main.scss, styles/light.scss ]
      dark: [darkly, styles/main.scss, styles/dark.scss]
  