# El reinado de Fernando VII

**Núcleo Temático:** el Antiguo Régimen y sus crisis.

## Reinado de Carlos IV

### Temor a la expansión revolucionaria (1788-1808)

El reinado de Carlos IV comienza en 1788, tras el inicio de la **Revolución francesa** (1789). Elimina **ministros ilustrados** (Jovellanos, Floridablanca), nombra a **Godoy Secretario de Estado** y **cierra la frontera con Francia** por **miedo** de la **difusión** de las **ideas revolucionarias** en España.

El protagonismo de las clases populares, el carácter radical de las reformas y la **muerte de Luis XVI** causan que **España entre en la coalición militar europea contra Francia** (1793-1795). Tras la derrota y la firma de la **Paz de Basilea**, España pasa a estar supeditada militarmente a Francia.

### Alianza con Francia

Tras la alianza con Francia, España participa en la batalla de **Trafalgar** contra Gran Bretaña, donde pierde casi toda la flota naval. Esto disminuye la explotación de las **colonias**. Para contrarrestar el efecto, Godoy **aumenta las contribuciones**, **desamortiza tierras eclesiásticas** y promociona las **Sociedades Económicas de Amigos del País**. Mientras tanto, la **nobleza e Iglesia se oponen a las reformas de Godoy**. A la vez, aparece el descontento popular causado por las epidemias.

### El motín de Aranjuez

En 1807, Godoy firma con apoyo de Carlos IV el tratado de **Fontainebleau**, por el cual las **tropas francesas pueden atravesar España para invadir Portugal**. Las tropas se sitúan en puntos estratégicos.

El 18 de marzo de 1808 estalla el **Motín de Aranjuez**, donde las clases populares, encabezadas por la nobleza y el clero, consiguen la **destitución de Godoy** y la **renuncia de Carlos IV**. Este último escribe una carta a **Napoleón**, quien decide invadir España y anexionarla.

### Abdicaciones reales y proclamación de José I

Napoleón llama a **Carlos IV** y a **Fernando VII** a Bayona para que **abdiquen en José I**, el hermano de Napoleón. En Bayona se redacta el **estatuto de Bayona**, ideado para reducir el Antiguo Régimen en España con medidas como el fin de la ~~inquisición~~, una desamortización eclesiástica y la desvinculación de los mayorazgos.

## La guerra de la Independencia y las Cortes de Cádiz (1808-1814)

### Levantamiento popular 

El 2 de mayo, tras las noticias de que Fernando VII había sido secuestrado por Napoleón, se produce un levantamiento popular. Este levantamiento es duramente reprimido, pero inicia un movimiento de resistencia popular que avoca en la creación de las **Juntas de Armamento y Defensa**.

### Actitudes frente a la ocupación francesa

Se forman dos bandos: afrancesados y patriotas. Además, la burguesía desea expulsar a los franceses de España para implantar el liberalismo.

### Desarrollo de la guerra

La retirada de las tropas de Napoleón para la guerra con Francia, el desgaste producido por la guerra de guerrillas y el apoyo de Reino Unido (general Wellington) hacen que Napoleón se vea forzado a firmar el Tratado de Valençay, el cual termina con la guerra y Fernando VII vuelve a España.

### Costes del conflicto bélico

Aumento de la **mortalidad** y **crueldad extrema**, además de un **freno económico** por la devastación de los campos de cultivo y el fin del sector lanero en Castilla. **Déficit de las finanzas**.

### Convocatoria de las Cortes en Cádiz

La Junta Suprema es reemplazada por la **regencia** del obispo Orense ante la **ausencia de Fernando VII**. El regente convoca las cortes, a pesar de los **problemas** para **reunir** a todos los **representantes**.

Las Cortes eran **unicamerales** y depositarias de la **soberanía nacional**. Después, reconocen a **Fernando VII** como rey y adquieren un **carácter revolucionario** para **acabar con los privilegios estamentales** e implantar la igualdad ante la ley.

### Constitución de 1812

También conocida como "la Pepa" por promulgarse el 19 de marzo de 1812. Esta constitución tiene como objetivo abolir el Antiguo Régimen.

**Medidas:**

- Creación de derechos, libertades y deberes.
- Sufragio universal masculino indirecto > 25: Los hombres mayores de 25 años podían votar.
- Fin de los privilegios, los señoríos, y los mayorazgos. Todos los ciudadanos son iguales ante la ley.
- Confesionalidad: la religión del estado era el catolicismo.
- Fin de la inquisición.
- El señor pasa a ser propietario, por lo tanto, ha de pagar a los asalariados o alquilar la tierra.
- Fin de los gremios.
- Desamortización.
- Milicias nacionales.

## Sexenio Absolutista (1814-1820)

### El regreso de Fernando VII

Tras llegar a Madrid, Fernando VII jura la constitución, pero, tras el **Manifiesto de los Persas** impulsado por la Iglesia y la nobleza, publica el decreto del 4 de mayo de 1814. En él, elimina el liberalismo, abole la Constitución de 1812, instaura el Antiguo Régimen, el régimen señorial y inicia persecuciones hacia los afrancesados.

### Vuelta al Antiguo Régimen

En Europa, el Congreso de Viena forma la **Santa Alianza**, que tiene el poder de intervenir en cualquier país para acabar con el liberalismo y las ideas revolucionarias.

España se enfrenta a los problemas de la **posguerra** (hambruna y mortalidad) y la **guerra** en las **colonias**, que además causa que la **Hacienda** real entre en **bancarrota**. Por último, el gobierno de Fernando VII es **incapaz** de dar **soluciones**.

### Aumento de la desafección social

Los campesinos no desean volver a pagar impuestos, mientras que la burguesía disfruta del desarrollo de empresas y negocios por la supresión de los gremios.

### Pronunciamientos liberales

El **descontento** generado entre los **militares** y **guerrilleros**, y la influencia ejercida por las **sociedades secretas** como los **masones**, causan **constantes pronunciamientos** para restablecer la **Constitución de 1812**. Todos ellos fracasan excepto el de **Riego** en 1820, que establece el Trienio Liberal y **fuerza** a Fernando VII a jurar la Constitución de 1812.

## Trienio Liberal (1820-1823)

### Medidas reformistas

El nuevo gobierno proclama la **amnistía** que permite que los afrancesados y los liberales puedan volver a España. Además, convocan elecciones ganadas por los **liberales**, que comienzan a abolir el **Antiguo Régimen** con medidas como una **desamortización eclesiástica**, el fin de los ~~gremios, mayorazgos y señoríos~~, restablecen la Milicia Nacional y crean las provincias y un código penal. A la vez de todo esto, Fernando VII aplica el derecho a veto para derogar leyes.

### Oposición y división del liberalismo

**Descontento** del **campesinado**, ya que, a pesar de poder ser arrendatarios y propietarios de la tierra, la gran mayoría son **jornaleros**.

Paralelamente, los liberales se dividen en dos: **moderados (doceañistas)**, que desean aplicar reformas que **no provoquen** conflicto entre el **rey** y la **nobleza**, y **exaltados**, que desean la aplicación de la **Constitución de 1812** de forma radical.

Mientras tanto, los realistas empiezan a controlar tierras como Cataluña o Navarra.

### La intervención militar de la Santa Alianza

Fernando VII solicita ayuda a la **Santa Alianza**, que manda a los **Cien Mil Hijos de San Luis**, encabezados por el duque de Angulema, para **restablecer el Antiguo Régimen**. Fernando VII se convierte en monarca absoluto y **deroga** los decretos publicados durante el **Trienio Liberal**.

## La pérdida de las colonias

Las ideas liberales e ilustradas, el éxito de la independencia de las colonias de EEUU, el apoyo de Reino Unido, conjuntamente con los impuestos y la discriminación de la metrópoli, causan que la **burguesía criolla busque la independencia**.

Durante la Guerra de Independencia (1808-1814), las colonias no aceptan a **~~José I ni a la Junta Suprema Central~~**. De hecho, crean sus propias juntas.

La independencia de las colonias es gradual y poco a poco pasan a ser nuevas repúblicas.

En 1824 sólo quedarán 3 colonias: **Puerto Rico

, Cuba y Filipinas**.

## Década Ominosa (1823-1833)

### Dificultades del reformismo

Creación de los **voluntarios realistas** para perseguir a los causantes de insurrecciones liberales. Ajusticiamiento de **María Pineda** y **fusilamiento de Torrijos**, ejemplos de la **represión fernandina**. Mientras tanto, la monarquía rechaza los intentos de reforma liberal.

### Quiebra económica

La pérdida de algunas colonias causa un freno económico.

La presencia de grandes problemas económicos causa algunas reformas: como la creación de los **presupuestos anuales** del estado, además de un **código de comercio** y el banco **San Fernando**. Además, la alta burguesía comienza a colaborar con el estado.

### El conflicto dinástico

Isabel (hija de Fernando VII) no puede ser reina por la **Ley Sálica** impuesta por **Felipe V**. Pero María Cristina fuerza a **Fernando VII** a promulgar la **Pragmática Sanción**, que abolía la Ley Sálica y hacía a **Isabel candidata al trono**. Los **carlistas** apoyaron a **don Carlos** (hermano de Fernando VII) como candidato al trono.

A pesar de ser una **disputa al trono**, también era la **disputa** entre el **absolutismo** de **don Carlos** y **María Cristina**, que para que su hija pudiera reinar buscó apoyos **liberales**. Con la enfermedad de Fernando VII, **María Cristina** fue nombrada **regente**, que formó un **gobierno liberal** y decretó una **amnistía para los liberales exiliados**.

En 1833, **Fernando VII muere**, **Isabel** pasa a ser **heredera** al trono y **María Cristina** pasa a ser **regente**.

### Ampliación de la Década Ominosa

{Este apartado no corresponde con ningún apartado del libro, sino con información adicional para complementarlo}

Los realistas se agrupan en partidas conocidas como *Malcontents* por la zona de Cataluña para reclamar al monarca el retorno total a las costumbres y tradiciones propias del absolutismo y el Antiguo Régimen, debido a que Fernando VII ahora necesita la colaboración de la burguesía de carácter liberal.

También durante este período aparece la propuesta de crear un cuerpo de policía para hacer frente a los liberales y a los masones que habían causado el pronunciamiento de Riego en 1820. De hecho, por este motivo y por su carácter ultrabsolutista, no se restablece la Inquisición.

Por último, para evitar futuros pronunciamientos e insurrecciones, Fernando VII ordena a sus ministros que acaben con cualquier cargo público que tuviera relación con las ideas liberales.

De este periodo también cabe destacar que, a partir de 1824, Cea Bermúdez se convierte en ministro, ya que posteriormente en la regencia de María Cristina será presidente del gobierno.

Fuente: [Decada Ominosa](http://bachiller.sabuco.com/historia/Decadaominosa%20psm.pdf)