Aquí tienes el texto corregido, respetando las negritas y los tachados:

# La crisis de la Restauración, la Dictadura de Primo de Rivera

**Núcleo Temático:** la Restauración y su crisis.

## El reformismo conservador y la Semana Trágica

### El relevo generacional en el liderazgo político

El inicio del siglo XX coincide con la **mayoría de edad de Alfonso XIII**. Además, tras los asesinatos de ~~Cánovas y Sagasta~~ se produce un **relevo generacional**, siendo sustituidos por **Maura y Canalejas**. Esto, junto con el **regeneracionismo**, causa **constantes cambios de gobierno**.

Además, aparece una **oposición política** conformada por nacionalistas y republicanos que desean acabar con los partidos dinásticos.

Asimismo, la industrialización causa **desigualdades regionales** y se produce una **radicalización del movimiento obrero**.

A todo esto, se une el **intervencionismo de Alfonso XIII** en la vida política de España, lo cual contribuye al desprestigio de la monarquía.

Por último, cabe destacar que durante el inicio del siglo y hasta el final de la Restauración (1874-1931) aumenta progresivamente la **presencia de militares**.

### La revolución "desde arriba" de Maura

**Maura** durante el **gobierno largo** (1907-1909) inició su **revolución desde arriba**: desde el gobierno proponía **regenerar el sistema político** e impedir una **revolución desde abajo**. Para ello realizó las siguientes reformas:

- **Ley electoral de 1907**: reducir el fraude electoral.
- **Ley de Administración local**: reducir el caciquismo, conceder más autonomía a ayuntamientos y diputaciones (descentralización) para frenar el nacionalismo catalán.
- Política social: **Instituto Nacional de Previsión** (similar a la Seguridad Social), además de legislación laboral (descanso dominical, leyes de protección frente a accidentes, condiciones de trabajo para mujeres y niños, y huelgas).
- **Medidas Proteccionistas**: fomento de la industria nacional y **Ley de Colonización interior** para fomentar la agricultura.

### La guerra de Marruecos

Después del desastre de 98, a España solo le quedan **colonias** en **África**.

Sin embargo, España incrementó su territorio tras la **Conferencia de Algeciras (1906)** y el **Tratado de 1912**, con la creación del **protectorado franco-español en Marruecos** para tratar de restaurar el imperio colonial. Además, aportaba **grandes beneficios económicos** (minas, obras públicas, inversiones en el ferrocarril).

Pero, los **beréberes** organizaban **cabilas**, lo que forzó a aumentar el número de militares en la zona. Finalmente, en el **barranco del Lobo** se produjo una masacre de tropas españolas, lo cual hizo que se mandaran **reservistas** a apaciguar el conflicto.

### La Semana Trágica y la caída de Maura

La Semana Trágica ocurrió en **Barcelona en 1909**, coincidiendo con el envío de tropas a **Marruecos**. Por ello, **republicanos, socialistas y anarquistas** trataron de iniciar una **huelga general**, lo que causó una **revuelta social** contra las fuerzas del orden y la iglesia.

Para frenar el conflicto, el gobierno decretó el **Estado de guerra** y mediante más de 200 **consejos de guerra**, logró frenar la revuelta. Destaca la ejecución de Ferrer y Guardia, impulsor de la Escuela Moderna.

Sin embargo, la repercusión de estas medidas causó la aparición de un **movimiento en contra del partido conservador**, bajo el eslogan ***¡Maura No!***, consiguiendo que Alfonso XIII cambiara el gobierno a los **liberales**.

### El fortalecimiento de la oposición

#### Republicanismo y Obrerismo

El republicanismo es la **principal fuerza de la oposición**. En 1903, aparece la **Unión Republicana** liderada por **Salmerón**. Tras su éxito en las elecciones de ese año, se integró en **Solidaritat Catalana** para acercar sus fuerzas regionalistas.

Esto disgustó a **Lerroux**, quien fundó el **Partido Radical**, mostrando un tinte republicano, anticatalanista y anticlerical, pero que declinará tras la Semana Trágica (1909).

Mientras, en Valencia aparece el **Blasquismo**, un movimiento republicano y anticlerical.

El **PSOE** en 1910 consiguió su primer diputado, **Pablo Iglesias**, en coalición con los republicanos. Sin embargo, no se integró en la Internacional Comunista, lo que causó una **escisión** y la aparición del **Partido Comunista de España** (PCE).

También aparece el **Partido Reformista**, donde destacan **Azaña y Ortega y Gasset**. El partido mantenía una ideología republicana, además de haber formado parte del último gobierno en 1922.

#### Carlismo

El Carlismo continuará manteniendo su influencia en Navarra, País Vasco y Cataluña. Aunque temporalmente se denominó **Jaimismo**, el Partido Carlista/Jaimista apoyó la llegada de la dictadura.

Además, sufrió otra **escisión** que dio lugar al **Partido Tradicionalista**. Sin embargo, con la llegada de la república, **carlistas**, **integristas** y **tradicionalistas** se unirán en la **Comunión Tradicionalista**.

***

## El reformismo liberal y el impacto de la Primera Guerra Mundial

### El reformismo liberal de Canalejas

El gobierno tomó algunas medidas de carácter liberal:

- **Ley de Mancomunidades** (aprobada por el gobierno de Dato): permitía que varias diputaciones se pudieran agrupar para gestionar determinadas competencias. Esta ley contribuía a la estabilización de los nacionalismos, aunque solo apareció la Mancomunidad de Cataluña.
- **Ley de Reclutamiento**: obligatoria para todo el mundo durante tiempos de guerra, además abolía la posibilidad de pagar para evitar el reclutamiento, aunque se podía pagar para una reducción.
- **Ley del Candado**: prohíbe el asentamiento de nuevas órdenes religiosas en España, lo que genera tensión con el Vaticano.
- **Impuesto progresivo sobre las rentas urbanas**, que sustituye al ~~Sistema de Consumos~~.
- Mejora de las condiciones laborales, prohibición del trabajo nocturno para las mujeres.

### Debilitamiento de los partidos políticos

La muerte de ~~Canalejas~~ (1912) a manos de un anarquista causó la **desestabilización** de los partidos dinásticos.

Para dirigir el Partido Liberal apareció el **conde de Romanones** y para el conservador **Dato**.

### El impacto de la Gran Guerra

A pesar de que el gobierno de Dato decretó la **neutralidad**, en España aparecieron movimientos sociales **germanófilos** y **aliadófilos**. Estos últimos destacaron en Cataluña, donde la victoria aliada se percibía como una victoria para Cataluña.

La **CNT** realizó un **congreso por la paz** en El Ferrol.

La neutralidad de España causó una **expansión económica**, exportando productos agrarios e industriales a los países beligerantes. Esto benefició especialmente a la siderurgia vasca, la minería asturiana y la industria textil y metalúrgica catalana. Sin embargo, también causó **un aumento de los precios en el mercado español**.

Como consecuencia de todo esto, se disparó la **inflación**, subida de precios no acompañada de un aumento de salarios, lo que contribuyó a **la separación entre las clases sociales** y causó **huelgas**.

***

## La evolución de los Nacionalismos

### Nacionalismos
#### Catalanismo

Tras el incidente de *Cu-Cut* y la **Ley de Jurisdicciones** que permite que los delitos en contra de la nación sean juzgados por **tribunales militares**, aparece la **Solidaritat Catalana** que agrupa a todos los Catalanistas, Carlistas y republicanos (~~Lerroux~~). Sin embargo, tras el incidente de la semana Trágica, la Lliga Regionalista apoya a Maura, lo que causa la destrucción de la coalición.

La **Mancomunitat** fue controlada por la **Lliga Regionalista**, desde donde se realizaron ciertas medidas para la modernización de Cataluña.

Por último, tras el fin de la **Gran Guerra** y otros hechos como la independencia de **Irlanda**, causan la aparición de partidos como **Estat Català** y **Acció Catalana**.

#### Nacionalismo Vasco

Muere ~~**Arana**~~. Siguen reclamando la **independencia y la autonomía**. Destaca la creación del sindicato del PNV, para obreros vascos de confesionalidad Católica.

### Regionalismos
#### Galleguismo

Aparece el partido político *A Nosa Terra*.

#### Andalucismo

Destaca Blas Infante con la propuesta del estatuto.

#### Valencianismo

Aparece el partido político *Unió Valencianista Regional*.

#### Aragonismo

Aparece el partido político *Acción Regionalista de Aragón*.

---

## El auge del obrerismo y la crisis de 1917

### La consolidación del sindicalismo de masas

Destaca el desarrollo de los sindicatos como **UGT**. En **Cataluña** aparece la **CNT**, la cual es un sindicato anarcosindicalista. Tiene como objetivo acabar con el capitalismo y crear una sociedad sin clases sociales y sin propiedad. Para ello recurren a huelgas y boicots.

### La conflictividad laboral y la nueva legislación

Durante la primera década del siglo XX, las **huelgas** van en aumento. Los obreros reivindicaban jornada laboral de 8 horas y el reconocimiento de los sindicatos para la negociación.

Con la creación del **Instituto de Reformas Sociales**, se empezaron a crear leyes para la regulación del trabajo, sin embargo, por la falta de una inspección eficaz.

### Cultura obrera y ateneos populares

Se empieza a difundir **educación entre obreros**, en lugares de encuentro como los **Ateneos obreros**. Aparecen pensadores como **Ferrer y Guardia** que difunden la **Escuela Moderna**.

### Crisis de 1917

La crisis se ve gravemente influenciada por la Revolución Bolchevique (1917) y por constantes protestas en contra del gobierno.

#### Militar

Los militares de la península estaban en desacuerdo con el **sistema de graduación por méritos** en Marruecos. Por ello se agrupan en **Juntas de Defensa**, desde donde demandaban subidas de salarios y sistema de **graduación por antigüedad**. Además, elaboran un **manifiesto**, de carácter **regeneracionista** donde hacen **culpable al gobierno de la situación del ejército**.

#### Política

El conde de Romanones, que a pesar de ser del partido liberal, aplica medidas conservadoras, cerrando las ~~**Cortes**~~ y gobernando mediante decretos. Sin embargo, la **Lliga Regionalista** decide formar su propio **gobierno provisional descentralizado** donde el PSOE, los nacionalistas y los republicanos están representados.

#### La huelga general (social)

La **CNT y la UGT** convocaron una **huelga general**. Por una parte se demandaba la creación de un **gobierno provisional** y la convocatoria de **cortes constituyentes**. Por otra parte, también solicitaban la **regulación de los precios**, los cuales habían subido mucho durante la Primera Guerra Mundial. Adicionalmente, durante la huelga el **republicanismo** empieza a ganar fuerza, frente a la política intervencionista de Alfonso XIII.

El gobierno ante esta situación aplica medidas de carácter **represivo**, declarando la **Ley Marcial**, la cual concedía más facultades a los militares para apaciguar la revolución.

---

## La descomposición del sistema parlamentario (1918-1921)

### Crisis económica y conflictividad económica

El fin de la ~~1ª Guerra Mundial~~ supone una **recesión para la economía**, lo cual incrementa el número de **huelgas**.

Destaca la huelga contra **La Canadiense**, empresa eléctrica de Barcelona que sufrió una huelga de 44 días. Hasta que patronal y sindicatos llegaron al acuerdo de **8 horas semanales**. Aunque se comprometieron a readmitir a los despedidos, nunca lo hicieron. Esto reavivó el conflicto y derivó en el **pistolerismo**.

Además, en Andalucía, Castilla la Mancha y Extremadura predomina la **toma de tierras** de **grupos anarquistas** influenciados por la revolución rusa. Además del inicio del **Trienio Bolchevique**.

### Los años del pistolerismo

Aparece la **Federación Patronal**, que es una agrupación de patronos que se unen para luchar contra el sindicalismo. Estos contrataban a **pistoleros a sueldo** que se utilizaban para acabar con los dirigentes obreros. Además la **Ley de Fugas** permitía a la policía disparar contra los detenidos en caso de fuga.

### Concentración y descomposición política

La crisis de 1917 tuvo consecuencias fatales en el sistema turnista. Ya que los partidos dinásticos se habían **debilitado** y **dividido**.

Ante esta situación aparecen los **gobiernos de concentración** que agrupaban a los políticos de **varios partidos políticos**. Destaca el **Gobierno Nacional** de Maura en 1918. Sin embargo, esto fracasa y se vuelve al sistema turnista. Sin embargo, los partidos no eran capaces de conseguir **~~mayoría parlamentaria~~**, esto desemboca en: **constantes cambios de gobierno, medidas de excepción, supresión temporal de las garantías constitucionales y la supresión del parlamento**.

### La guerra en el protectorado: Annual

Tras el fin de la ~~Primera Guerra Mundial~~ tanto España como Francia desean continuar con la conquista de Marruecos. Donde los militares (denominados **africanistas**) ascendían rápidamente por los **méritos de la guerra** y la **política intervencionista de Alfonso XIII**.

Por ello en 1921, el general **Silvestre** es enviado para **consolidar la ocupación**. Sin embargo, un ataque en **Annual** organizado por **Abd-el-Krim**, arrasó con el ejército dejando más de **13,000 muertes**.

Esto resultó en una **opinión pública** contraria a la guerra, los republicanos y socialistas presionaban para abandonar Marruecos, y para que **alguien asumiera las responsabilidades del desastre**. Por ello el gobierno nombró una **comisión militar de investigación** dirigida por el general Picasso.

El **Expediente Picasso** incriminaba a parte de los militares pero también a ambos partidos dinásticos y sobre todo a **Alfonso XIII**. Cuando el documento fue enviado a las Cortes la Campaña Republicana y Socialista salía claramente beneficiada. Sin embargo, para evitar el conocimiento de las conclusiones del expediente, se produjo el **golpe de estado de Primero de Rivera**.

---

## La dictadura militar de Miguel Primo de Rivera (1923-1931)


### El golpe de estado militar

Antes del golpe de Estado, en el panorama político: el gobierno de **García Prieto** proponía una reforma de la Constitución (1876) liberal para: **reducir la influencia de la iglesia**, **reformar la ley electoral** (para acabar con el caciquismo) y **reducir la influencia del rey y del ejército**. Sin embargo, el rey, los militares y la iglesia se opusieron a esta reforma.

Esto último, conjuntamente con el **expediente Picasso** que incriminaba a la monarquía y al ejército como culpables del **desastre de Annual**. Y el éxito del **fascismo en Italia** causa el Golpe de Estado de Miguel Primo de Rivera. El golpe, que contaba con un manifiesto donde se planteaba la dictadura como **regeneracionista** para acabar con el **~~caciquismo, corrupción y la conflictividad obrera~~**. Además de garantizar la **estabilidad** y el **orden público**.

La dictadura recibió el **apoyo de todos los sectores, salvo de la CNT**, la cual trató de impedirlo con un intento de huelga general.

### La construcción del régimen dictatorial

Primo de Rivera pasa a ser **presidente de gobierno**, e inicia el **directorio militar (1923-1925)**.

Se suprime la **Constitución**, **las Cortes**, **la Mancomunidad** (conjuntamente con la prohibición del uso de los símbolos catalanes). Se ilegalizaron los **sindicatos**, **partidos políticos**. Además se crea un **Estatuto municipal** y otro **provincial** para acabar con el ~~caciquismo~~. También, se suprimen **los ayuntamientos**. Adicionalmente, para garantizar el **orden público** se recurre a medidas represivas.

Además, durante la primera parte de la dictadura con el **desembarco en Alhucemas (1925)** Abd-el-Krim se rinde, lo cual implica un éxito en el gobierno de España sobre Marruecos. También se caracteriza por el fomento de obras públicas para hacer remontar a la economía.

### La organización corporativa del Estado

Durante el **Directorio Civil (1925-1930)**, se trata de asentar el **régimen definitivamente y darle continuidad**. El cual tenía un carácter **corporativo** similar al fascismo italiano. También se crea la **Asamblea Nacional Consultiva**, conformada por miembros que representaban distintas instituciones públicas.

Para ello se creó la **Unión Patriótica**, un partido gubernamental que apoyaba al partido. Estaba conformado mayoritariamente por el clero, funcionarios y caciques. Además, se reimplanta el **Somatén**, agrupaciones de civiles armados para la preservación del orden público.

Por último, aparece la **Organización Corporativa Nacional**: agrupaba a obreros y patronos y trataba de regular los conflictos laborales mediante **Comités Paritarios**. La **UGT** decidió integrarse mientras que la **CNT** no y fue duramente perseguida.

### La oposición a la dictadura

La dictadura en sus inicios **no tuvo oposición**, sin embargo, irá apareciendo progresivamente.

La primera oposición destacable la encontramos en la **sanjuanada (1926)** que fue **duramente reprimida**.

Progresivamente aparecerán organizaciones como la **Alianza Republicana** (Lerroux, Azaña [futuro presidente de la república]), la **Agrupación al servicio de la república** de (Ortega y Gasset) y la **Federación Universitaria Española**, que se posicionaron claramente en contra del régimen dictatorial.

Las medidas anticatalanistas causan la oposición de los grupos regionalistas como la **Lliga Regionalista**. Además, aparece el nacionalismo republicano de la mano de Macià.

Por último, los obreros se oponían desde la **CNT**, la cual sufrió una escisión dando así lugar a la aparición de la **Federación Anarquista Ibérica (FAI)**. Por último, el **PSOE** y el **PCE** se opusieron a la dictadura.

### El hundimiento de la dictadura

La oposición causó que **Alfonso XIII** retirara el **~~apoyo a Primo de Rivera~~**. Que dimitirá en **1930**. El general **Bereguer** es nombrado presidente para realizar unas elecciones y volver a la normalidad constitucional. Este periodo es conocido como **dictablanda**.

Mientras tanto, los republicanos, nacionalistas y obreristas acuerdan en el **Pacto de San Sebastián (1930)** acabar con la monarquía e instaurar la república.

**Bereguer** es sustituido por el almirante **Aznar** el cual convoca unas elecciones municipales el **12 de abril de 1931**. Las cuales se transformaron en un **plebiscito** a favor o en contra de la monarquía.

### El inicio de la 2ª República: "España se despierta republicana"

En las elecciones del 12 de abril de 1931, triunfó la coalición republicano-socialista. Se puede resumir con la frase de **Aznar** "un país que se acuesta monárquico y se despierta republicano". Hubo constantes proclamaciones de la república durante los siguientes días y al final **Alfonso XIII se exilia**, poniendo fin a la **~~Restauración~~**.
