# Desarrollo y crisis del Franquismo (1960-1975)

## Liberalización económica y desarrollo

### Plan de Estabilización

El fracaso de la autarquía llevó al estado a una gran crisis económica (inflación, déficit comercial…) que vio como única solución pedir ayuda a organizaciones INT como OECE o FMI, las cuales pedían a cambio reformas liberalizadoras y fin de la autarquía. Los nuevos gobiernos franquistas con nuevos integrantes tecnócratas, vinculados algunos al Opus Dei; incentivaron la elaboración de un Plan de Estabilización 1959. Era una reforma profunda del sistema económico cuyo plan principal era salir de la crisis y acabar con la autarquía.

- Reducir la inflación limitando los créditos y congelando salarios →Estabilizar la economía

- LIberalizar el mercado interior → Eliminando organismos interventores
- Liberalizar el mercado exterior → Facilitando la entrada de mercancías extranjeras e inversión de capitales. Además, algunos organismos INT concedieron préstamos a ESP

### Planes de desarrollo 

Era una planificación orientativa que trataba de mejorar la inversión pública y privada, y transformar la geografía industrial, la cual fue llevada a cabo en tres planes. Para controlar su función se creó una Comisaría del Plan de Desarrollo presidida por López Rodó, tecnócrata ministro de economía, vinculado al Opus Dei. Se llevaron a cabo acciones estructurales con la inversión en infraestructura y productos industriales y polos de desarrollo para reducir los 

desequilibrios regionales. Los resultados fueron muy limitados ya que los recursos se invirtieron de 

forma ineficiente. Sus objetivos no se cumplieron y su mayor logro fue dotar al país de algunas infraestructuras y de materias básicas.

### La industria, motor del desarrollismo

- Aumento del 10% anual gracias a la mejora de productividad, inversión extranjera, a la importación de maquinarias; tecnología; petróleo… ,y la incorporación de mano de obra del campo con bajos costes salariales.
- Diversificación de la producción industrial con el auge del sector metalúrgico(automóviles y electrodomésticos), la electricidad, el sector químico(farmacéutico,plásticos, detergentes), y la alimentación.
- Concentración en zonas con mayor tradición fabril aunque también por nuevas zonas como Madrid y Valencia. También destacar el aumento de la construcción vinculados al éxodo rural de las personas del campo a la ciudad.

La necesaria financiación de las actividades económicas fue la que produjo un gran desarrollo del sector bancario →invirtió grandes cantidades de dinero y realizó numerosos préstamos.

La agricultura se moderniza → factores estimuladores

- Éxodo rural hacia el extranjero y zonas industriales que redujo la mano de obra
- Mejora de la producción gracias a la mecanización, fertilizantes químicos y el regadío
- Diversificación de la producción gracias al cambio de la dieta de la población→ crisis cerealística y aumento de los huertos frutícolas y ganadería por la nueva demanda

### La población crece y se desplaza

#### Años 60

La población experimentó un gran crecimiento gracias al aumento de la esperanza de vida(70 años para hombres 76 para mujeres), la alta natalidad y el descenso de la mortalidad infantil (mejora de la higiene, alimentación); el resultado fue un aumento de la población joven y vieja. También se emprendió una política natalista con el fomento de la familia, el rol de la mujer, el cine… También se produjeron  movimientos migratorios tanto interiores como extranjeros(una de las cosas que salvó al franquismo)(mención a las remesas y divisas). Con el éxodo rural en busca de mejores oportunidades laborales y sociales se produjo un fuerte desequilibrio territorial Cambio del mercado laboral

#### Años 60-75
Se produjo una gran reducción de los trabajadores agrarios mientras que el sector con más trabajadores pasó a ser la industria y se produjo un aumento del sector terciario(transporte, comercio, sanidad,...). Esto fue un reflejo de la transformación de la sociedad. La participación femenina aumentó pero no de forma considerable ya que la maternidad seguía suponiendo una barrera profesional. La Ley sobre Derechos de la Mujer 1961 puso fin a las discriminaciones más graves → obligación de abandonar el trabajo por matrimonio.

### La llegada del turismo masivo

Entre 60-73 se produjo un aumento de más de 30 millones de turistas, esto supuso un aumento de las actividades hoteleras, del trabajo y un gran aumento económico gracias a la llegada de divisas extranjeras. Sin embargo esta afluencia era solo estacional “sol y playa” y se concentró en las zonas costeras sufriendo una aceleración urbanística caótica y un escaso respeto a la naturaleza.

## Fragilidad del desarrollismo

### Dependencia exterior

El crecimiento económico supuso un crecimiento del PIB mayor a la media europea, un incremento de la calidad de vida y un incremento del salario del 40% por habitante. Este resultado no fue tanto gracias a la política española como a su aprovechamiento de la expansión económica de la época en Europa.  Estos recursos financieros invertidos llegaron a españa mediante las remesas de los emigrantes, las divisas de los turistas y las inversiones de empresas extranjeras. 

Estos recursos consiguieron equilibrar la balanza de pagos por la tecnología, maquinaria y productos que eran necesarios para mejorar la estructura productiva.

### Lejos del estado de bienestar europeo 

La dependencia exterior implicaba grandes gastos y subordinación a los intereses de las empresas extranjeras. El desarrollo exigía el aumento del gasto público en los servicios y la inversión en infraestructuras. El aumento que se produjo fue insuficiente y derivaba de la reforma fiscal inadecuada que se implementó aumentando las tributaciones(impuestos recaudados) sobre el trabajo y el consejo. También se implementó un insuficiente sistema de seguridad social financiado por las cotizaciones y con escasa contribución estatal. Todo esto alejó a España del estado de bienestar. La dictadura fue ineficiente en el impulso de infraestructuras, redistribución de rentas y en la continuidad del crecimiento económico. La crisis del petróleo de 1973 puso en evidencia estos problemas y la fragilidad del sistema.

## Una sociedad en transformación

### Crecimiento urbano u perferias

Se produjo un aumento de la población urbana que se concentró en las ciudades más grandes mientras que los municipios menos poblados y mayormente rurales experimentaron una pérdida de población. Se formaron grandes áreas metropolitanas en las ciudades que concentraban a mucha población. Estas áreas incluían varios municipios(periferias) los cuales pasaron a estar superpoblados  concentrando  miles  de  personas.  El  desarrollo  urbano  creció  de  forma desordenada por lo que aparecieron grandes bloques de vivienda de mala calidad con tal de contestar a la demanda de viviendas, a pesar de que el ritmo de construcción seguía siendo insuficiente.

### Una nueva estructura social

Crecimiento económico y modernización impulsaron el desarrollo de una sociedad capitalista avanzada con amplios sectores de trabajo y una clase media en desarrollo. Se caracterizó por:

- Pérdida de peso del mundo rural →reducción de los pequeños propietarios y jornaleros

- Aumento del proletariado urbano →por primera vez en la historia había más obreros industriales que campesinos. Muchos antiguos jornaleros agrícolas se ocuparon de los sectores menos cualificados y se ubicaron en las zonas más industrializadas.

- impulso de la clase media asociada a la industria(talleres automovilísticos, eléctricos…), a los servicios(turismo,comercio…), a la administración y a la enseñanza y sanidad. 

- Burguesía asociada a empresas internacionales y al sector público. También se produjo un aumento de los funcionarios y la aristocracia seguía existiendo.

### Arranque de la sociedad de consumo

Gracias al aumento del salario, se produjo un incremento del poder adquisitivo de la población lo que incentivó el consumismo. Los hogares se equiparon con modernos electrodomésticos y se popularizó el automóvil, sobre todo a partir del SEAT 600.  Se convirtieron en nuevos hábitos las vacaciones, el incremento del ocio y los espacios culturales. La publicidad que convertía a los artículos en deseo ayudó a la instalación de la sociedad de consumo →aún inferior a la europea.

### Nuevos comportamientos sociales y formas de vida

Con las transformaciones sociales se fue llevando a cabo un progresivo abandono del rígido clima de posguerra formando una sociedad moderna más abierta, esto a medida que se imponían los hábitos culturales europeos.

- Proceso de laicización y secularización que alejaba a la sociedad de la tutela de la iglesia del primer franquismo → progresiva pérdida de poder de esta

- Acceso  a  la  enseñanza  básica,  incluidas  las   mujeres,  y  aumento  de  los universitarios →Ley  General  de  la  Educación  de  1970  reorganizó  el  sistema educativo

- Modificación de la estructura familiar, pasamos de la familia amplia a la familia nuclear(padres e hijos) por la reducción del espacio en contraste al mundo rural. Esto también fue impuesto por la influencia ejercida por el cine y los viajes al extranjero.

- Cambio del papel de la mujer con el acceso a los estudios, la propagación del feminismo y su inclusión en el trabajo asalariado

- La eclosión de la juventud

## Reformismo sin democratización

El franquismo necesita cambiar su imagen

En el aniversario número 25 desde la victoria franquista → gran operación de propaganda para dar una imagen de paz y progreso. Los gobiernos de los 60, con cada vez más presencia de tecnócratas fueron partidarios del desarrollo económico y de la renovación de la política del país. Esto comportó un conjunto de reformas políticas para dirigir el régimen hacia estas transformaciones y tapar algunos de los aspectos autoritarios del franquismo. También mejorar su imagen ante la CEE adaptándose a los patrones sociales pero sin reconocer las libertades fundamentales ni la democracia. Este tímido reformismo tenía la convicción de que el bienestar generado en la sociedad consolidaría el régimen franquista y compesaría la falta de democracia.

### La continuidad de la represión

A pesar de todo se mantuvo el apartado represivo como pieza fundamental. El único cambio relevante fue la desmilitarización parcial a partir de la creación del Tribunal de Orden Público 1963- 77( jurisdicción civil para los delitos del ejército ante las libertades políticas). 

Los consejos de guerra continuaron, siendo los peores aquellos en los que se imponía la pena de muerte, generando rechazo incluso en el exterior. Muchos dirigentes fueron ejecutados incluso aquellos acusados de delitos que después de demostró que no habían cometido. También se recurrió al estado de excepción para frenar movilizaciones y acabar con la oposición//(Violencia policial).

### Las reformas institucionales y legislativas

- 1966 nueva Ley de Prensa, promovida por Manuel Fraga y en la cual se suprimió la censura previa pero imponía sanciones si el contenido no era apropiado. Se estimuló la participación de trabajadores en las elecciones sindicales→ dotar de + representatividad a la Organización Sindical.

- 1967 Nuevas leyes como la de libertad religiosa(la católica seguía siendo la  principal) o la de elección de procuradores familiares de las cortes. La nueva ley fundamental→  Ley  orgánica  del  Estado  confirmaba  la  institucionalización monárquica del régimen, fijaba los poderes del jefe del Estado, separación de este con el nuevo presidente del gob, y actualizaba la Ley de Cortes

- 1969 Reforma Ley de Sucesión → Franco designaba a Juan Carlos como sucesor y a la monarquía como sucesora del franquismo “Todo a quedado atado y bien atado”

### Discrepancias entre las familias por las reformas

Las corrientes se dividían entre quienes defendían el reforzamiento del Movimiento, los que promovían una apertura limitada como fraga y los tecnócratas que pretendían reducir el poder del Movimiento siendo partidarios de ser más flexibles. En 1969 el escándalo Matesa(empresa de maquinaria textil vinculada al Opus Dei) provocó una crisis gubernamental. Este caso de corrupción fue difundido por la prensa por lo que los inmovilistas denunciaron la excesiva tolerancia informativa; por lo que se retornó al inmovilismo. La crisis acabó con la victoria electoral de Carrero blanco y la formación del gobierno monocolor que supuso la salida de Manuel Fraga y José Solís, responsabilizados de la contestación social.

## Los nuevos movimientos sociales y el antifranquismo

### Conflictividad y movimientos sociales

Se produjo un aumento de las huelgas y manifestaciones en forma de reivindicaciones laborales, esto supuso el aumento del conflicto en zonas obreras e industriales. La represión hizo que los antifranquistas denunciasen la violencia, la falta de libertades y derechos. En este clima surge la CCOO de forma clandestina para impulsar la lucha laboral y la política. Esta se introdujo dentro del sindicato vertical y, a pesar de que el régimen lo sabía, lo permitieron. Su éxito en las elecciones provocó su ilegalización y sus representantes fueron juzgados por medio del proceso 1001. A parte de CCOO surgieron otras organizaciones obreras como la USO/UGT.

### Protestas de estudiantes y barrios de vecinos

La protesta universitaria creció y supuso uno de los mayores problemas del régimen, sobre todo con la reivindicación de la amnistía, de sindicatos en contra de la SEU y la exigencia de libertades. La radicalización de la movilización supuso la colaboración europea y marxistas, y el aumento de la represión en los campus. Se formaron comités que rechazaban la nueva Ley de Educación y exigían la democratización de las Universidades. En los últimos años del franquismo los campus se convirtieron en espacios de agitación permanente.*(no tan importante)*

La falta de servicios(viviendas, escuelas, asfaltado, alcantarillado y transporte) supuso la movilización de asociaciones de vecinos. Los alcaldes se vieron desprestigiados por la inacción ante las demandas y la represión por lo que se demandaron ayuntamientos democráticos.

### La división de la iglesia

El sector de la iglesia había mantenido su apoyo al régimen hasta que el Papa ascendió al arzobispo aperturista Vicente Enrique y Tarancón a cardenal lo que supuso un punto de inflexión. Este pidió la reconciliación “vencedores y vencidos”→”Tarancón al paredón”. La iglesia comenzó a perder su influencia debido al proceso de secularización de la sociedad, por lo que comenzó a aumentar la posición antifranquista dentro de la iglesia. La división de la iglesia puso en evidencia la debilidad de uno de sus pilares lo que afectó profundamente a Franco.

### La agitación nacionalista

En Cataluña se llevó a cabo un movimiento de reivindicación de la lengua y la cultura pérdidas junto con la autonomía en 1939. La Asamblea de Cataluña fue un organismo que popularizó el lema “Libertad, amnistía, estatuto de Autonomía”. Esta reunía a partidos antifranquistas como PSUC y partidos históricos como ERC y UDC (La ERC se mantuvo poco activa).

En el País Vasco, aparte de que el PNV era un referente para el gobierno vasco en el exilio, el hecho de mayor repercusión fue la aparición de ETA en 1959. Esta organización revolucionaria y nacionalista radical llevo a cabo una lucha armada contra el franquismo con atentados contra figuras de renombre. Estos hechos eran aplaudidos por parte de la sociedad.

###  Los partidos de la oposición

Em 1960 de produjo una recomposición del antifranquismo debido a las transformaciones sociales y a la pérdida de influencia del exilio político. Estas fuerzas empezaron a desacreditar a la dictadura por las duras condiciones de vida y la falta de libertades políticas , y reivindicaron la necesidad de superar la Guerra Civil, y la democracia. Por una parte, el PCE fue el partido más activo desde la clandestinidad a pesar de tener varios problemas internos, y por otra parte, el PSOE, con menor presencia, estuvo presidido por Felipe González tras el Congreso de Suresnes.

También se creó una oposición moderada formada por disidentes del propio régimen decepcionados por la política represiva y antidemocrática, En  1962 gran parte de la oposición moderada junto con republicanos y socialistas  en  el  exilio  participaron  en  el  Congreso  de  Munich  para  denunciar internacionalmente al Franquismo →Forma despectiva “Contubernio de Munich”.

## Crisis y agonía del franquismo

### Carrero Blanco y la continuidad del régimen

En 1969 el gobierno tenía a Carrero Blanco como vicepresidente y se mantuvo firme la política inmovilista con el endurecimiento de las leyes. Su intención de acabar con los conflictos internos fracasó cuando se volvieron a enfrentar tecnócratas y falangistas ante la nueva Ley Sindical. 

En 1973 Carrero Blanco fue nombrado presidente del gobierno, persona clave para asegurar la continuidad del franquismo tras la muerte de franco. Esto se vió frustrado tras su asesinato en un atentado de Madrid dirigido por la ETA. 

La figura de Carrero era ultra católica y muy metódica. ETA quería dar un gran golpe para liberar a los presos y no fue hasta que no se fueron los embajadores de la USA y la CIA, por contexto de la guerra fría y la relevancia de la PCE, que no pusieron en marcha el golpe. Este murió junto a su escolta y chofer y la operación se llamó “Operación Ogro”.  Esto aumentó las diferencias entre los que estaban completamente a favor del régimen, el búnker, y quienes necesitaban un cambio progresivo, los aperturistas.

En 1974 de formó un nuevo gobierno presidido por Carlos Arias que pretendía unir a aperturistas e inmovilistas, con un proyecto de reforma aperturista. Pero Arias no convenció ni a franquistas ni a la oposición.

### Movilización social

Desde 1970 aumentó la oposición obrera, estudiantil y vecinal por lo que los gobiernos aumentaron la represión, lo que atemorizó a la población. Ante la inminente desaparición del Caudillo la oposición creó organismos unitarios para formar una alternativa al régimen→ La junta democrática en parís (PCE, izq, CCOO) y la Plataforma de Convergencia

Democrática en torno al PSOE.  Ambos proponían un gobierno provisional que proclamarse la amnistía y convocase elecciones. Finalmente se acabaron fusionando en 1976. En estos años hubo un aumento de la violencia ya que ETA incrementó sus atentados con matanzas indiscriminadas, además de los practicados por el FRAP y del GRAPO. En respuesta el gobierno de Arias incrementó la represión.

### El Conflicto del Sáhara

Francia pactó con el rey  de Marruecos la independencia de la zona francesa sin informar al gobierno de España que se vió forzado a hacer lo mismo con el protectorado español. Tras un conflicto armado España cedió el territorio de Ifni a Marruecos. Para proceder con la descolonización el gobierno aceptó celebrar un referéndum a propuesta de la ONU y del Frente Polisario. En 1975, aprovechando la enfermedad de franco Marruecos exige el territorio por lo que organizaron la Marcha verde(Invasión pacífica del Sahara). Ante el peligro por comenzar un conflicto con Marruecos y con Franco al borde de la muerte, el gobierno de Arias decidió ceder el territorio firmando el Acuerdo de Madrid

### 20N Muerte de Franco

Con la condena internacional del franquismo y las tensiones en el Sahara el 20-N franco falleció dejando un Estado en evidente crisis y con la imposibilidad de un Franquismo sin Franco.
