# El franquismo: una larga postguerra (1939-1959) 

## Las bases de la dictadura

### Los pilares del régimen

- **El ejercitó**: apoyo más destacado, tuvo una participación activa en el poder y fue el instrumento básico de la represión política. Más del 40% de los ministros fueron militares. Estos ocuparon cargos importantes como gobernadores civiles o semblantes.
- **El Partido único:**, el movimiento, fue el gran difusor del discurso del régimen con su control de los medios y propaganda. Enroló a la militancia más activa del franquismo y creó entre la sociedad organizaciones de masas par ampliar su influencia: Frente de juventudes, para el adoctrinamiento de la juventud; sección Femenina, formar a la mujer con espíritu cristiano y nacionalsindicalista; La SEU que pretendía encuadrar a los universitarios; la CNS y el Sindicato vertical que integraba patrones y trabajadores.
- **La iglesia:** tuvo un gran papel en la defensa y justificación del régimen → se definió como Estado confesional católico. Obtuvo beneficios económicos → presupuesto de culto y clero, se instauró como máxima autoridad educativa e impuso la moral católica a la población. Esta unión con el Estado dio lugar al nacionalcatolicismo→ identificación con el Estado, la nación española y la religión. Este pilar fue el primero en caer.

### Las “familias” del franquismo

Participación política → Llevada a cabo por aquellos quienes habían mostrado unión con el “Caudillo”, incorporaban diversos grupos que rivalizaban por el poder:

- **Los militares:** estrechamente vinculados a Franco y subordinados por el poder militar
- **Los falangistas:** era la tendencia más fascista y pretendía que el Partido estuviera por encima del Estado. El partido estaba sometido al poder de Franco y destacaron en la propaganda →Control de los medios y de la movilizaciones,también en la administración.
- **Los carlistas:** defendían el tradicionalismo pero tuvieron que desistir en la defensa del derecho de sucesión, hecho que generó conflictos internos.
- **Los monárquicos:** aunque Franco no tenía intención de restaurar la monarquía mantuvo algunas relaciones con el heredero, Juan de Borbón, el rey que no reinó. La influencia de este grupo fue creciendo.
- **La iglesia:** única institución que podía formar asociaciones al margen del Movimiento. De este modo se formaron grupos influyentes como la Asociación Católica Nacional de Propagandistas (ACNDP) y, sobre todo, el Opus Dei que tuvo gran influencia en la segunda etapa. La rivalidad entre falangistas y católicos fue constante.

### Las actitudes sociales y políticas

La dictadura contó con el apoyo de las clases altas y sectores derechistas que recuperaron la influencia perdida durante la Segunda República. También fue importante el soporte de los pequeños y medianos propietarios agrícolas del Norte → habían respaldado el alzamiento militar. Las Clases medias, que habían quedado desbordadas por la Guerra Civil y que se encontraban frente a un nuevo orden, actuaron de forma pasiva ante la dictadura. Así a pesar del rechazo que la dictadura inspiraba el trauma bélico les atemorizaba. Las Clases populares, perdedoras de la Guerra y por ello vigiladas y reprimidas, generaron una oposición contra la dictadura. Aunque una minoría ejerció actitudes de oposición, el miedo, el control policial y la miseria condujeron a una pasividad política.

## La consolidación del régimen franquista

### La adaptación a una coyuntura exterior variante

El régimen estuvo condicionado por el desarrollo de la IIGM. Cuando Franco apoyó al Eje activamente los falangistas quisieron forjar un Estado fascista, esta perspectiva estuvo encabezada por el cuñado de Franco, Ramón Serrano. La evolución de la guerra obligó a Franco a moderar su política para aproximarse a los vencedores. Primero, destituyó a Serrano Suñer, que representaba la opción germanófila y generaba tensiones. Poco después, se retornó a la neutralidad y se eliminaron los signos más radicalmente fascistas(saludo con el brazo en alto) y se promulgaron Leyes Fundamentales que crean nuevas instituciones y legalidad jurídica.

### Las Instituciones del régimen

- **Leyes Fundamentales del régimen** (no es una ~~constitución~~)

- **1938 Fuero del Trabajo**  la cual regulaba las relaciones laborales y establecía los principios del nacionalsindicalismo. 
- **1942 Ley Constitutiva de las Cortes** que establece la división de los poderes, por mera formalidad, pues estaban subordinados al Caudillo que mantenía todos los poderes. Las cortes, por tanto, solo tenían una función consultiva y de preparación de las leyes para el gobierno. Podían estar integradas por procuradores designados por el gobierno y Franco o como representantes de la Organización Sindical o corporaciones profesionales.

- **1945 Fuero de los Españoles:** declaración de derechos de los españoles subordinada a los principios del movimiento y sin garantía para poder ejercerlos.
- **1945 Ley de Referéndum Nacional:** única vía de participación política popular. El jefe del estado podía someter a consulta las cuestiones que considerase oportunas.
- **1947 Ley de Sucesión:** establecía a España como reino representado por el caudillo y preveía la monarquía como sucesora del franquismo.

La Ley de Unidad Sindical organizó los Sindicatos Verticales dentro de la CNS inspirándose en el modelo corporativo italiano (por tramos de producción y sometidos a la autoridad del delegado de Falange). Por otra parte, se impulsó el carácter centralista y unitario del Estado con la abolición de los estatutos de autonomía y la marginación de las lenguas y culturas diferentes a la impuesta. Y se restableció la antigua estructura de las Capitanías Generales en cada provincia  con un gobernador militar (Gobernadores civiles).

### El aparato represivo

El estado de guerra se mantuvo hasta 1948. Continuaron los campos de concentración y los batallones de trabajo → para redimir con la reconstrucción de puertos, caminos, valle de los caídos… Muchos detenidos pasaron consejos de guerra que carecían de garantías jurídicas, no sólo se aplicaron a los vencidos sino también a aquellas actividades contrarias al régimen. Las ejecuciones →pena de muerte se detuvieron en 1952. Se retomaron más restringidas en 1963.

La represión se amparaba bajo leyes como : la Ley de Represión de la Masonería y el Comunismo 1940, la Ley de responsabilidades políticas 1939, la ley que regulaba el delito de rebelión militar 1943 y la Ley de Represión del Bandidaje y Terrorismo 1947. Se forzó a la población a delatar a los llamados “enemigos de España”. Finalmente se crearon las fuerzas policiales militarizadas de Guardia Civil y el Cuerpo General de Policía →objetivo defender el Estado. La tortura fue práctiva habitual para destruir la oposición política e impedir protestas.

### El aislamiento internacional 

La recién creada ONU condenó al Franquismo por su ayuda a las potencias fascistas derrotadas. El gobierno de Francia cerró la frontera con España y en la Asamblea General de las Naciones Unidas se recomendó la retirada de los embajadores. A pesar de esto Franco se mantuvo firme en perpetuar el poder. Este aislamiento comportó que España quedase excluida del Plan Marshall 197 y de la OTAN constituida en abril de 1949.

## Los años 50 años bisagra

### Reconocimiento internacional

Los años 50 fueron una etapa intermedia entre  el retroceso económico de los 40 y el crecimiento de los 60. El régimen se vió favorecido por la guerra fría que cambió al enemigo de la democracia de fascismo a comunismo. En consecuencia las relaciones mejoraron. Desde inicio de los 50 se establecieron ayudas económicas de parte de EEUU ,y España se fue abriendo al mercado internacional lentamente. El régimen procedio a reforzar su discurso anticomunista y católico con inciativas como el nuevo gobierno de 1951, dentro del cual estaba Carrero Blanco como máximo consejero de Franco.

 Encontramos también indicios de la reconciliación a nivel internacional con el concordato de la santa sede de 1953, el cual marcaba el nacionalcatolicismo y fijaba la confesionalidad del estado y la autoridad de la iglesia en la educación. España se integró en la onu en 1956 e hizo un acuerdo con USA en el que permitía la instalación de bases militares a cambio de ayudar económicamente al país.

### Inicio de la recuperación económica

La tímida entrada al mercado occidental permitió el acceso a materias primas, fuentes de energía y maquinaria que permitió la mejora económica, además se eliminaron las cartillas de racionamiento. Se produjo un aumento de la productividad. El resultado fue una progresiva recuperación económica que permitió igualar y superar los niveles económicos previos a la guerra civil.

### La crisis de 1956-1959

Se inició una crisis importante que obligó a hacer reformas económicas como el Plan de Estabilización. Las causas fueron:

- Nueva oleada de huelgas por motivos laborales, la represión fue dura pero los trabajadores consiguieron un aumento del salario
- El inicio de la disidencia estudiantil en universidades que demandaban reformar la enseñanza y elecciones libres de delegados estudiantiles en contra de la SEU. El régimen respondió con detenciones y expulsiones
- La crisis económica causada por la inflación, el déficit comercial y la escasez de divisas

En 1957 Franco nombró un nuevo gobierno formado por tecnócratas vinculados en su mayoría al Opus Dei, a petición de Carrero Blanco. Estos participaron en la toma de decisiones económicas por la liberalización de la economía y siguieron los consejos del Banco Mundial y la OCDE. Así daba inicio un crecimiento económico a partir de los 60

## Los años del hambre

En los años 40 España experimentó una gran crisis económica cuya recuperación fue un proceso muy lento, por lo que el estado se acabó encerrando en una autarquía. Este sistema basado en la autosuficiencia económica de un país y caracterizado por el intervencionismo del estado en la materia económica supuso la eliminación de los vínculos con el exterior y la fijación de la producción y los precios de venta por parte del gobierno. Se tomaron medidas como la regulación del comercio exterior, el fomento de la industria interior y el control de la producción agraria. La escasez de esta última supuso la aparición de las cartillas de racionamiento las cuales iban destinadas a cada familia (diferenciadas aún entre vencedores y vencidos). 

El dirigismo estatal fue insuficiente para garantizar el acceso a los productos básicos. Debido a esto es que surgió el mercado negro, lugar en el que se podía acceder a estos productos por un precio mayor, ya que se operaba en clandestinidad. Este era dirigido por estraperlistas, los cuales se beneficiaron de la situación. Debido también a que los agricultores no obtenían suficiente beneficio vendiendo sus productos al estado, estos escondían parte para venderla en el mercado negro. Esto conllevó a que no se pudiesen garantizar las cartillas por la falta de productos. 

Con todo este panorama, junto con las duras condiciones laborales, los bajos salarios y la elevada inflación; se creó un panorama de fuerte deterioro de las condiciones de vida. Generando así un clima de hambre y miseria, en contraste de las personas que se beneficiaban del mercado negro. El hambre provocó el resurgimiento de enfermedades que ya habían sido erradicadas y la miseria se manifestó en la carencia de viviendas dignas con un aumento del chabolismo y del uso de cuevas como viviendas.

## La oposición del sistema

Los monárquicos demócratas propusieron unirse a  Don Juan de Borbón con el objetivo de oponerse al régimen por lo que tomaron la iniciativa con el Manifiesto de Lausana.

Por otra parte encontramos a los maquis los cuales eran un grupo de republicanos armados que se escondieron en el monte a la espera de que acabase la guerra en Europa y que con la ayuda de las tropas aliadas acabar con el Franquismo. Las guerrillas que protagonizaron tuvieron escaso éxito. Finalmente, tras la caída del nacismo llevaron a cabo la invasión del valle de Arán.

Entre los años 46 y 47 comenzaron a haber conflictividades en los sectores industriales con huelgas generales en Cataluña y País Vasco, a pesar de que las huelgas estuviesen prohibidas durante el régimen. Destacó la movilización de la huelga de tranvías en el 51, causada por la subida de precios del billete de tranvía. Esta derivó en una huelga general con un éxito inesperado, pues se anuló el aumento de las tarifas y hubo represiones en autoridades de Barcelona.