# Un Golpe a la democracia: la guerra civil (1936-1939)

## Las causas de la guerra

La democracia en Europa estaba en crisis, la mayoría de las creadas a partir de la IGM caían una detrás de otra siendo sublevadas por golpes totalitaristas. La República española fue víctima de un golpe de estado militar en 1936, que derivó en una guerra civil.

### Reacción conservadora y radicalización social

En 1936 la república había generado enemigos internos muy poderosos que, al ya no estar en el poder y estar en  contra de las reformas políticas y sociales implementadas, decidieron acabar con la situación y recuperar el poder a través de un golpe de Estado.

El retorno de las reformas tras las elecciones de febrero , estimuló tanto la reacción conservadora contra el gobierno como la radicalización de algunos sectores de la izquierda que demandaban cambios más profundos. La conflictividad social creció y enfrentó a fuerzas contrarias crispando la situación: derecha vs izquierda (Fasc. Tradi. y Monarq. vs Comu. Anarq. y Soci.). A pesar de todo, el Gobierno republicano consiguió mantener el control del orden.

### La rebelión militar rompe el orden constitucional

El grupo militar que pretendía acabar con el orden democrático fue dirigido por Mola y tuvo apoyo de oficiales del ejército, de la UME (asociación clandestina oficiales antirrepublicanos) y de fuerzas políticas extremistas. El general Sanjurjo,desde Lisboa, fue jefe del proyecto golpista.

El 17 de julio se inició el golpe en el protectorado, donde se desplazó Franco para tomar el control al día siguiente, cuando éste triunfó. En la península la acción fue impulsada por generales como Mola(Pamplona),  Queipo(Sevilla),Goded(Mallorca)  y  Cabanellas(Zaragoza).  También consiguieron implicar a grupos civiles armados (falangistas, requetés…) e imponerse a las fuerzas republicanas. Ocuparon gran parte del territorio pero la República consiguió mantenerse gracias a movilizaciones obreras, fuerzas políticas y militares fieles al orden vigente.

### Del alzamiento a la Guerra Civil

La República había preservado las provincias más pobladas, los centros del poder central y tenían un control de la  flota, la aviación y de la industria; pero no había acabado con la sublevación. Sin embargo, el gobierno había perdido el control de las calles y los mecanismos de seguridad. Por su parte, los sublevados necesitaban trasladar a la península al ejército de África que suponía el grueso de su poder militar. Por lo que la intervención exterior fue decisiva, contrastando la pasividad de las democracias con la intervención de los fascistas. Aviones italianos y alemanes trasladaron  las  tropas  mediante  un  puente  entre  Tetuán  y  Sevilla  y  proporcionaron recursos( armas, soldados, técnicos, dinero…). Así se iniciaba la Guerra Civil. 

### España dividida en dos

**España sublevada** (zona agraria y algunas ciudades): Sus apoyos se definían como nacionales y estaban en oposición a la República; conservadores, falangistas y carlistas, grupos católicos y monárquicos, y los contrarios a las reformas. Los objetivos eran dispares: organizadores (dictadura  militar,  falangistas  [régimen  fascista]),  Carlistas  (monarquía  tradicionalista  y Monárquicos [retorno Alfonso]).

**España republicana** (centros industriales y zonas de agricultura de exportación): apoyo de las clases populares; obreros y campesinos sin tierras; de tendencia socialista, comunista y anarcosindicalista, también clases medias urbanas y un grupo de intelectuales y artistas. Apoyaban al Frente Popular pero tenían intereses diversos: algunos más reformistas y otros más revolucionarios de tendencia anarquista. Eran citados como “rojos” por los sublevados.

## La república en guerra(I): de la revolución de 1936 a mayo de 1937

### El estallido revolucionario

Durante los tres años de guerra sucedieron tres gobiernos: José Giral (jul-sep 1936), Largo Caballero (sep1936-mayo1937) y Juan Negrín (mayo1937-marzo1939). En primer lugar, el gobierno de Giral tuvo que hacer frente al proceso revolucionario desencadenado el 18 de julio. Gran parte de los que lucharon en las calles entendían que el triunfo sobre los rebeldes suponía la necesidad de un nuevo orden social. Por esta razón se formaron comités y organismos diversos con el objetivo de instaurar un nuevo orden revolucionario. El gob de Giral, desbordado, pasaba a un segundo plano en este nuevo escenario dirigido por anarq, soci y comunist.

Las fuerzas revolucionarias procedieron a la persecución de los partidarios de la rebelión y de aquellos que, por su ideología, representaban al viejo orden: capitalista y conservador. Se incrementaron los asesinatos y encarcelamientos de religiosos, grandes empresarios y “sujetos sospechosos”, así como el saqueo e incendio de iglesias → anticlericalismo y antiburgués. Las Checas eran los lugares en los que se  interrogaba a estos “sospechosos” sometiendolos mediante torturas. 

Los comités revolucionarios postularon una sociedad más igualitaria y antiautoritaria adoptando medidas como la colectivización de tierras, empresas y transportes. En paralelo se creó un nuevo discurso de la mujer que buscaba la equiparación en la vida política y social. En las ciudades se extendió el control obrero de talleres y fábricas, la sociedad se proletarizó. En añadidura, para combatir a las fuerzas sublevadas se crearon columnas de milicianos y milicianas, en sustitución del ejército tradicional.

### El gobierno de Francisco Largo Caballero

A finales de agosto de 1936 las milicias no conseguían frenar el avance sublevado. El gobierno de Giral, formado únicamente por republicanos, no tenía dicha capacidad ya que no era equiparable con el conjunto de fuerzas antifascistas movilizadas el 18 de julio. Se optó por formar un gobierno de coalición dirigido por Largo Caballero, de mayoría socialista, y con presencia de republicanos y comunistas . Dos meses después se incorporaron cuatro representantes de la CNT, entre los cuales estaba, Federica Montseny (primera ministra de España). La entrada de anarquistas a un gobierno se convirtió en un hecho histórico, que se produjo como emergencia cuando los sublevados entraron en Madrid. 

El nuevo gobierno avanzó en la recuperación de la autoridad, por lo que comenzó a centralizar el poder y suprimir algunas juntas y comités. Se esforzó en poner fin a la violencia y canalizar la revolución. Cambió la estrategia bélica con la creación del Ejército Popular→ movilización obligatoria de la población masculina y la incorporación de columnas militarizadas, y la formación de brigadas mixtas.

### La crisis de mayo de 1937

{completada con hechos de mayo}

Los cambios fueron los que dieron visibilidad a las tensiones dentro de las fuerzas antifascistas. Por un lado, un sector socialista encabezado por Indalecio Prieto y los comunistas cuestionaron a Largo Caballero para dirigir la guerra y consideraron necesaria la unificación del mando. Por otro lado, los anarcosindicalistas y grupos radicales insistían en avanzar en la revolución para implantar un nuevo orden social. También se oponían al freno de las colectivizaciones.

En Barcelona, estas tensiones acabaron derivando en un enfrentamiento abierto. Cuando la Generalitat desalojo a los anarquistas del edificio de Telefónica que habían ocupado, se precipitó una lucha armada en la calle entre quienes apoyaban al gobierno (rep, soci y comu) y militantes de la CNT y el POUM. Hubieron varios muertos y heridos por lo que el gobierno central tuvo que actuar enviando fuerzas policiales. La derrota de los revolucionarios más radicales significó la pérdida de influencia de la CNT y la liquidación del POUM, y que provocó una gran crisis política y la caída del gobierno de Largo Caballero.

### La evolución  de los frentes (julio  1936 - marzo 1937)

Tras el fracaso del golpe militar → Primer objetivo de los sublevados →Tomar Madrid. Tras cruzar el estrecho las tropas de África, al mando de Yagüe, enlazaron con la zona sublevada Norte. En septiembre, Franco, nombrado jefe del ejército tras la muerte de sanjurjo, ocupó Toledo y puso fin a los ataques sobre su Alcázar. A finales de octubre se encontraba a las puertas de Madrid. Ante la amenaza el Gobierno decretó la movilización → “No pasarán” y “Madrid, tumba del fascismo”. En noviembre el Gobierno se traslada a Valencia. Poco después tuvieron lugar las “sacas”, fusilamientos de presos para fusilarlos, llevadas a cabo por los republicanos.

Vicente Rojo era quien dirigía la estrategia militar republicana e impulsó la reorganización del ejército con las Brigadas Mixtas, con este impulso se pretendía obtener mayor eficacia militar. Madrid resistió gracias a la llegada de las primeras Brigadas Internacionales y de la Columna Libertad, al mando del anarquista Durruti. Franco quedó atascado por lo que decidió continuar la conquista de Andalucía con la ocupación de Málaga en una operación que fue ensayo de la “guerra relámpago” por parte de las fuerzas italianas →Persiguieron despiadadamente a los ciudadanos que huían. De forma paralela, impulsó una maniobra envolvente para aislar las comunicaciones de la capital con Valencia. Los republicanos cortaron ambos intentos  imponiéndose  en la batalla del Jarama(feb 1937), con la intervención de las Brigadas internacionales y de Guadalajara, donde derrotaron a las tropas italianas. Franco optó por renunciar a la conquista de Madrid y empezar una guerra de desgaste, y consolidar su poder de Caudillo. Con esto desplazó su objetivo a la zona norte.

## La República en guerra (II): de mayo de 1937 a la derrota de 1939

### El gobierno de Negrín

Tras la crisis del gobierno el presidente Manuel Azaña nombró  a Juan Negrín para formar un gobierno integrado por los partidos sin lso sindicatos, los comunistas adquirieron mayor relevancia. Su vinculación con la URSS, casi que la única ayuda, explican esta situación. El gob de Negrín centralizó el poder, reorganizó al ejército y reprimió a los anarquistas, y el POUM fue ilegalizado y perseguido; su dirigente Andreu Nin fue asesinado por los servicios secretos rusos. Negrín presentó el programa de los Trece Puntos(1938) para poder mostrar una República sólida y una política de resistencia. Este presentaba la República como una democracia liberal, eliminaba toda intrusión extranjera y proclamaba una amnistia.Franco rechazó la propuesta.

El desfavorable desarrollo de la guerra retorno las disputas internas. A la política de resistencia de negrín se le opusieron los que vieron necesario un acuerdo con franco al precio que fuese ya que consideraban la guerra perdida.

### Resistir es vencer

Desde 1938 la escasez generaba malestar y los bombardeos muchas víctimas. Las condiciones de vida eran alarmantes y el desencanto se extendía. Negrín basaba sus esperanzas en que el inicio del conflicto en Europa salvase a la Rep. ya que provocaría la ayuda exterior y la marcha de alemanes e italianos del país →”resistir es vencer”. Esto se vio liquidado con el Pacto de Múnich 1938, y de nada ayudó la retirada de las Brigadas Internacionales. La derrota del Ebro asestó un nuevo golpe a la filosofía de Negrín.

### Evolución bélica →Ruptura del territorio republicano (marzo 1937-julio 1938)

Con la nueva estrategia franquista de atacar el norte las tropas atacaron Bizkaia. Poco después la legión Cóndor alemana destruyó Gernika. Bilbao fue ocupada en junio y la República reaccionó con ataques que no consiguieron evitar la entrada en Cantabria y Asturias. Debido a su superioridad armamentística y organizativa. Los republicanos llevaron una ofensiva contra Teruel que a pesar de tener éxito inicial no pudo frenar la contraofensiva que siguió por Aragón, penetró en Cataluña  y llegó a Vinaroz (marzo 1938), la república quedó dividida en dos zonas.

### La batalla del Ebro (julio - noviembre 1938)

Tras el hundimiento del frente de Aragón el republicano Vicente Rojo planteó la batalla del Ebro→ Triple objetivo: mostrar que se puede resistir, frenar la ofensiva y restablecer la unidad del territorio. Empezó el 25 de julio de 1938 con el ataque republicano que cruzó el río Ebro. Franco envió grandes refuerzos, junto con aviones y artillería alemana e italiana. Los combates fueron muy duros y se prolongaron durante tres meses hasta que las tropas franquistas los hicieron retroceder hasta el punto de inicio. Esta fue la batalla más sangrienta de la guerra.

### La derrota republicana

El ejército republicano quedó muy dañado y sin capacidad de defenderse en Cataluña , por lo que las tropas de Franco entraron casi sin resistencia. Miles de personas huyeron al exilio junto al gob. de Negrín siendo perseguidos por el ejército rebelde y su aviación. El 10 de febrero los nacionales llegaron a la frontera francesa y la cerraron. La República quedó sentenciada por dos hechos. En primer lugar, el gob de Franco fue reconocido por Reino Unido y Francia, y Azaña presentó su dimisión. En segundo lugar Casado, jefe de defensa, impulsó un golpe de estado contra Negrín. Ello provocó un enfrentamiento interno que facilitó la ocupación de la capital 28 de marzo y poco después las tropas entraron en Valencia,proclamándose la victoria el 1 de abril.

### Las consecuencias de la guerra

- **Número de víctimas:** más de 600k. Además de los muertos por bombardeos, heridos, mutilados, desaparecidos…  y más de 470k que marcharon al exilio. 
- **Perdidas económicas:** infraestructuras y comunicaciones destruidas, más las viviendas afectadas por los bombardeos, y el endeudamiento por la ayuda milir prestada.
- **Política:** la guerra destruyó el sistema democrática que fue sustituido por una dictadura.
- **Social:** diferenciación clara entre vencedores y vencidos.

## La España sublevada: la construcción del nuevo Estado totalitario

### Un nuevo poder: Franco, “Caudillo” único

En el territorio ocupado denominado zona nacional se proclamó un estado de guerra por parte de los alzados, los cuales procedieron a liquidar la resistencia republicana (este estado duró 9 años). Se esperaba que  Sanjurjo tomase el control desde Portugal pero murió en Lisboa en un vuelo por una supuesta sobrecarga el 18 de julio de 1936. Esto hizo que pensar que pudiese haber algún tipo de complot, Mola también murió en un vuelo( Franco no volvió a viajar en avión) 

El 24 de julio se creó en Burgos la Junta de Defensa Nacional integrada por generales militares y presidida por Miguel Cabanellas.  Poco después se procedió a unificar el mando y eligieron a Franco, a quien Hitler y Mussolini reconocieron como único interlocutor, como jefe. El 1 de octubre fue nombrado Generalísimo y jefe del estado. La junta Técnica sustituyó a la de Defensa u se organizó  en  comisiones  cuyas  decisiones  debían  ser  aprobadas  por  Franco.  Continuó concentrando poder: jefe del Partido Único (1937) y presidir gob (1938) hasta Caudillo.

### El sistema represivo

El estado de guerra se extendió por todo el territorio nacional e implantó un sistema para castigar a aquellos que se opusieron al alzamiento: los detenidos serían juzgados en consejos de guerra; juicios rápidos y sin garantías. A los defensores de la Rep. se les aplicaba el delito de rebelión militar con penas que podían llegar hasta la muerte. 

Desde el 19 de agosto de 1936 las autoridades fueron creando campos de concentración para los prisioneros de guerra. Sometidos a duras condiciones, eran clasificados por su adscripción ideológica: los “afectos” al régimen salían en libertad, los “desafectos leves” obligados a realizar trabajos forzosos y los “desafectos” trasladados a la prisión en espera de ser juzgados en un consejo de guerra.  Los prisioneros aumentaron de 13k-280k, estaban concentrados en celdas, sometidos a violencia, adoctrinamiento y bajo unas condiciones insalubres; lo que aumentaba la mortalidad.

La violencia tuvo una dirección específica hacia las mujeres. Se expresó, por un lado, en la violencia sexual que sufrieron las mujeres durante las ocupaciones y en los centros de detención, y por otro, en las humillaciones por “rojas” (se les rapaba la cabeza para marcarlas).

### La imposición de la España única

Esta imposición, basada en los valores de la tradición y del imperio, significó el fin de la descentralización y de los sistemas autonómicos. Por una parte, la ocupación en 1937 del País Vasco significó la anulación de los acuerdos económicos de Vizcaya y Guipúzcoa por no haberse 

sumado a la sublevación. Por otra parte, la llegada de las tropas a Cataluña en 1938 supuso la abolición del estatuto de Cataluña, la generalitat y de la lengua en el ámbito público.

### La guerra, una cruzada

La rebelión tuvo gran simpatía por sectores conservadores católicos y la mayoría de la jerarquía eclesiástica. Esto debido a que desde 1931, habían mostrado su desconfianza en la república, su oposición a la ley sálica y defensa de los privilegios institucionales. 

Tras el 18 de julio surgieron movilizaciones religiosas en defensa de la España tradicional. A pesar de las excepciones que hubo en este sector (que tuvieron que pagar con la vida o exiliarse)  la mayoría se vio potenciada por la violencia anticlerical acontecida durante el periodo anterior.

La visión de Cruzada quedó establecida oficialmente con la Carta Pastoral en la que los Obispos daban apoyo a los sublevados, esto tuvo un importante impacto internacional. Se defendía el alzamiento al haber impedido el triunfo de una revolución comunista y la iglesia víctima de ello.

### El Partido único: el decreto de unificación 

Los sublevados prohibieron todos los partidos del Frente popular y dejaron solo como legales a Falange Española Y de las JONS cuyo jefe fundador José Antonio Primo de Rivera había sido ejecutado en 1936 por los Rep, la Comunión Tradicionalista (carlistas). Los monárquicos, católicos y conservadores de la CEDA simplemente eran tolerados. Se suspende Const. 1931

Las tensiones entre los que apoyaban a la sublevación fueron aumentando por lo que Franco, inspirándose en el fascismo italiano y alemán promulgó el Decreto  de Unificación (19 de abril de 1937). Partido único; Falange Española Tradicionalista y las JONS (carlistas y falangistas), bajo el mandato de Franco el “Caudillo”. Así constituyendo el Movimiento Nacional. El uniforme de dicho partido → camisa azul de Falange, boina roja carlista y el saludo fascista con el brazo en alto. Las resistencias eran acalladas con el destierro o la prisión, por lo que creció la afiliación.

### El Gobierno de Burgos

En 1938 se creó el primer gobierno de la zona nacional, con Franco como jefe del Estado. Con integración de las distintas tendencias aliadas. Este Gobierno se ciñó sobre todo a la tarea de desarrollar el marco legal de la represión:

- La ley de prensa: control del Estado sobre las publicaciones con censura previa.
- La ley de depuración de funcionarios públicos: permitía expulsar de su puesto a quienes no estuviesen comprometidos ideológicamente.
- La ley de responsabilidades políticas: prohibía partidos, sindicatos y asociaciones, e imponía multas a personas denunciadas por simpatías o militancia repúbli. desde 1934.

También se emprendió la organización nacionalsindicalista del Estado con el Fuero del Trabajo (marzo de 1938), la primera de las leyes fundamentales del nuevo Estado. Inspirada en el fascismo  italiano,  prohibía  los  sindicatos  de  clases  (UGT,  CNT…),  las  huelgas  y  las reivindicaciones obreras, y establecía un único sindicato corporativo que integraba empresarios y trabajadores bajo control de la Falange. ( Tambíen fin del matrimonio civil y divorcio)

### La Victoria

Tras la “Victoria” proclamada por Franco el 1 de abril de 1939, continuó la división del país, ahora entre vencedores y vencidos y la exclusión social de los segundos. El nuevo Estado inspirado en el fascismo defendía un modelo consevador, tradicional y católico. Los componentes fueron cambiando a conveniencia de Fraco y la “zona nacional” se convirtió en un Estado totalitario.