
# La liberalización, la regencia de MªCristina, el reinado de Isabel II y el Sexenio Democrático

## La primera guerra carlista (1833-1840)

### Dos opciones enfrentadas

Tras la muerte de Fernando VII, se inicia la el conflicto entre **Isabel II** y **don Carlos Mª Isidro** que **inicia una insurrección** armada que deriva en una guerra civil. Dejando de lado la batalla por el trono también era una batalla entre Absolutismo y Liberalismo

Los carlistas gastan el lema ***Dios, Patria y Rey/Fueros***, tenían el **apoyo del clero, la nobleza agraria y los campesinos** y controlaban **País Vasco, Aragón, Cataluña y Valencia**, los cuales se habían visto afectados por la eliminación de los fueros. Además del apoyo internacional de **Rusia, Prusia y Austria**

Mientras que los isabelinos tenían el apoyo de **alta nobleza, funcionarios reformistas y miembros de la jerarquía de la iglesia y liberales moderados**, además contaban con el apoyo de **Francia y Reino Unido**.

### Desarrollo

Carlos María Isidro reclama el trono en el **Manifiesto de los Abrantes**. Los carlistas controlan Navarra y País Vasco además de zonas de Valencia y Aragón. Carlos María Isidro instala una **zona Carlista** y organiza un estado. Al principio de la guerra, los Carlistas van avance hasta que, la ofensiva **isabelina** liderada por **Espartero**.

En 1839 se firma el **Convenio de Vergara** que restablece los fueros únicamente en Navarra y las provincias vascas. La **guerra acaba en 1840.**

### Consecuencias de la guerra

- Gran numero de muertos
- Los **liberales** se dividen en **progresistas y moderados**, además de presencia militar en los gobiernos
- Crisis y deuda ↑↑; Desarrollo Industrial ↓↓

***
## Revolución Liberal (1833-1843)

### Régimen del Estatuto Real, Acceso progresistas al poder

María Cristina, forma un gobierno con Cea Bermúdez, que con sus mediadas tímidamente reformistas, conceden una **amnistía** y crean una división de provincias. Es sustituido por Martínez de la Rosa que promulga el **Estatuto real**, que forma **Cortes, estamentales, consultivas**, con un sufragio mínimo. Esto confirma la **división** entre liberales **moderados y progresistas**. Sin embargo, este gobierno no es capaz de afrontar el hambre, las epidemias, los ataques de los carlistas y los motines.

Por eso María Cristina establece a Juan Álvarez **Mendizábal** como presidente que para derrotar al carlismo convoca una **quinta** de 100.000 de hombres, reforma el Estatuto Real para darle un sentido liberal al país y un **desamortización**{5ª}. Pero, **Mendizábal** es destituido por los **moderados** que toman el **gobierno**.

Finalmente los progresistas se revelan a favor de la constitución de 1812. Con un **pronunciamiento de sargentos en la Granja**, María Cristina acepta la **Constitución de 1812**. Calatrava pasa a ser presidente con Mendizábal de ministro de hacienda

| Nº        | 1                                               | 2                                                                                | 3                                                                              |
| --------- | ----------------------------------------------- | -------------------------------------------------------------------------------- | ------------------------------------------------------------------------------ |
| Gobierno  | Cea Bermúdez                                    | Marínez de la Rosa                                                               | Mendizábal                                                                     |
| Ideología | Absolutista, levemente liberal                  | Liberal moderada                                                                 | Liberal progresista                                                            |
| Medidas   | Amnistía liberales, división país en provincias | **Estatuto Real (1834)** Cortes estamentales consultivas                                    | Quinta 100.000 hombres, reforma liberal, **desamortización** y reforma agraria |
| Problemas | Guerra Carlista, descontento liberales          | Guerra Carlista, descontento liberales progresistas, hambre, enfermedad y motines | Descontento liberales conservadores                                            |


### El desmantelamiento del Antiguo Régimen (Constitución de 1837)

El gobierno de Calatrava plantea una **Monarquía Parlamentaria**, además promulga la **Constitución de 1837 (progresista)** que plantea la **Separación de poderes**, **soberanía nacional**, Monarquía Parlamentaria, 2 cámaras (aparición del **Senado**), el sufragio censatario y la confesionalidad del estado. Es muy breve ya que leyes orgánicas regularan otros aspectos.


### Liberalización del sistema económico (Reforma agraria)

El sistema liberal instaurado impulsa una **reforma agraria**. Los **Señoríos desaparecen** y pasan a ser propietarios de sus tierras las cuales tienen que alquilar o contratar trabajadores (jornaleros). Se desvinculan los **~~Mayorazgos~~**, y continua la **Desamortización de Mendizábal**. Que tiene como objetivo la recaudación de dinero para la guerra carlista, disminuir el déficit de hacienda y generar una clase de propietarios que defienda el régimen liberal.

Además de la desaparición de: **~~Gremios, Mesta, Diezmo y privilegios~~**. Lo cual establece la **Libertad de contratación y de industria**

### La vuelta al poder de los moderados (1837-1840)

Tras aprobar la constitución se convocan **elecciones**, que ganan los **moderados**, que abolen la **~~Constitución de 1837~~**, **gobiernan** por **decreto**, **frena** a la **desamortización** de **Mendizábal** y **restringen las libertades ↓↓**. Promulgan la **Ley de ayuntamientos**, que otorga a María Cristina la capacidad de elegir los alcaldes de las capitales de provincia. 

Los progresistas tras estas medidas inician revueltas ciudadanas, María Cristina apoya a los moderados, pero los progresistas con el **liderazgo de Espartero**, ganan y **María Cristina se exilia**

### La regencia de Espartero (1840-1843)

Convoca **elecciones** que dan **mayoría** a los **progresistas**. Espartero deroga la **~~Ley de Ayuntamientos~~** y opta por una **regencia única**, incrementa la **presencia** de los **militares** en el **gobierno**.

Incrementa las **libertades ↑↑**, mientras que aparecen los **movimientos republicanos y obreros**.

Negocia el **arancel librecambista**, que permitía la venta de productos textiles ingleses en España, lo que enfurece al sector textil catalán y causa un **levantamiento en Barcelona**, que Espartero frena **bombardeando** la ciudad

En 1843 un **movimiento militar** encabezado por **O'Donnell y Narváez** respaldado por los **moderados** causa el exilio **~~Espartero~~**.

Con esta situación y la incapacidad de nombrar una nueva regencia las **Cortes** adelantan la mayoría de edad y se **convierte** en **reina** a **Isabel II** con 13 años

***
## La Década Moderada (1844-1854)

### Las bases del régimen moderado

De las **elecciones** de **1844** el general **Nárvaez** y los **conservadores** salieron ganadores. Nárvaez desea acabar con la **~~etapa revolucionaria~~** con medidas represivas para conseguir **estabilidad política**. La **oligarquía propietaria**, nobles y burgueses que compran tierras nacionales, predominan.

También se aprueba la **Constitución de 1845 (moderada)**, cuyas características son: soberanía nacional, separación de poderes, sistema **bicameral** la confesionalidad del estado, y el **sufragio censatario**. Además, de restringir ~~libertades~~.

Por último se firma el **Concordato con la Santa Sede** que pone termina con la ~~Desamortización de Mendizábal~~ y la iglesia **reconoce a Isabel II como reina**, además del sustento del **culto y clero**.

### Desarrollo del Estado Liberal Moderado

Aparece el **sistema electoral por distritos uninominales**, que es fácilmente manipulable, **reforma fiscal (Ley Món-Santillán)**, aparece el impuesto de consumos, la **Guardia Civil** sustituye a la ~~Milicia Nacional~~, los **alcaldes** **elegidos** por la corona aparece el **Código Civil** y el **Código Penal**, el sistema métrico decimal y la educación pública.

### Crisis del moderantismo

Los gobiernos moderados no consiguen la **~~estabilidad~~**, tuvieron 16 gobiernos en 10 años. Además de enfrentarse a las **camarillas**, **huelgas** y **motines**, lo cual causa la segunda guerra Carlista ("**Guerra dels matiners**").

Mientras tanto aparece el **Partido Demócrata** que defiende el sufragio universal,  por último el gobierno de Bravo Murillo, que suspende las **~~Cortes~~**, y **gobierna por decreto**, lo cual causa la oposición de los progresistas.

***
## El Bienio progresista (1854-1856)

### Revolución de 1854

Ocurre la **Vicalvarada** pronunciamiento **progresista** de **O'Donnell** que firma el **Manifiesto de Manzanares** escrito por **Cánovas del Castillo**. Que fuerza a Isabel II a restablecer la **Milicia Nacional**, aumentar las libertades y disminuir los impuestos. Además, acepta un gobierno con **Espartero** como **presidente** y **O'Donnell** al **Ministerio de Guerra**.

Por último, se convocan Cortes constituyentes para promulgar la **Constitución de 1856** la cual es conocida como la "**Non Nata**".

### La nueva legislación económica

\[6ª\] **Desamortización de Madoz**, desamortización civil y eclesiástica. Además aparece la **Ley General de Ferrocarriles**, la cual incentiva a la construcción de líneas de ferrocarril, lo cual atrajo a inversores extranjeros. Además de la ampliación de la red de carreteras, el sistema de telégrafo, la minería, la sociedades por acciones y las entidades bancarias.

<span style="color: grey">{Truco para aprender las medidas: sin contar la desamortización, van de dos en dos: Desamortización, Ley General de Ferrocarriles - Ampliación red carreteras, telégrafo - minería y sociedades por acciones - entidades bancarias }</span> 

### Los problemas sociales

Elevada mortalidad, **crisis de subsistencia**, además del clima de conflictividad social.

En Cataluña, aparece la **conflictividad obrera** aparecen las asociaciones de trabajadores, además de la **primera huelga general** (1855).

En Castilla, se enfrentan a levantamientos de campesinos.

### La Crisis del Bienio Progresista

**O'Donnell** propone medidas represivas, lo cual causa que **Espartero resigne**. **O'Donnell** se convierte en **Presidente**, suspende las Cortes, la milicia y las libertades. El cual recibe una **moción de censura**. 

***
## La desintegración de la monarquía (1857-1868)

### Reacción moderada 

**Narváez** es nombrado **presidente** por la reina para establecer de nuevo el **moderantismo** y un gobierno autoritario. Se promulga la **Ley de Instrucción Pública** del ministro **Moyano**, que establecía el sistema de enseñanza y la **Iglesia** como **inspectora**. Establece el **Senado vitalicio**. Además de **movilizaciones** de **republicanos y demócratas**, por las malas cosechas.

### El gobierno unionista de O'Donnell (1858-1863)

La reina nombra **presidente** a **O'Donnell**, líder de ***La Unión Liberal***. Que **liberaliza Constitución de 1845**, reformando la **Ley Electoral**, y dota de **autonomía ayuntamientos**. Es colocado para generar estabilidad y **detener los pronunciamientos** constantes en España

Para la economía del país, **continúan desamortización de Madoz** y continúan con el fomento **ferrocarril**.

Además de varias campañas de carácter internacional como: la **expedición a Cochinchina**, **intervención en México** para obtener el cobro de unas deudas fracasas y las **campañas militares de Marruecos**, lideradas por **Prim** y O'Donnell. Con la **paz de Wad-Ras** España incorpora a **Ifni**.

### La crisis del final del sistema (1863-1868)

El **intervencionismo de la reina**, que vuelve a poner a Narváez como presidente y la **influencia de las camarillas** causan **inestabilidad política**. 

Los **demócratas y republicanos en contra de Isabel II** por la **Noche de San Dáñela (Emilio Castellar)**. 

Se produce el pronunciamiento de **sargentos en del cuartel general de San Gil** y **Narváez** cierra las **~~Cortes~~**, y se enfrenta a una **crisis de subsistencia**.

Progresistas, Demócratas y Unionistas firman el **Pacto de Ostende**, que acaba con la monarquía de **~~Isabel II~~** y forman un gobierno provisional ^a4824a

***
***
## El Sexenio Democrático (1868-1874)

### La gloriosa revolución de 1868

La **crisis de la monarquía** causada por el **Pacto de Ostende**. Conjuntamente con **crisis económica** producida por: **crisis financiera** (Escaso rendimiento de las inversiones ferroviarias, causa que bajen las acciones y aumenta la deuda pública), la **crisis industrial** (Generada por subida del precio de la materia prima el algodón, la guerra de Secesión Americana y el "Hambre de Algodón") y la **crisis de subsistencia** (sucesión de malas cosechas y el incremento del precio del trigo). Además de la **oposición social** de los obreros y industriales.

Todo esto causa la **gloriosa revolución de 1868**, iniciada por el **Manifiesto "España con honra"** escrito por **Prim, Serrano y Topete**. Denuncia la **corrupción monarquía**, **defiende las libertades** y propone formar un **gobierno provisional** y elecciones a Cortes.

El pronunciamiento causa la aparición de **Juntas revolucionarias**, que exigen: **sufragio universal masculino**, **derecho de asociación**, **educación gratuita**, abolir **~~impuesto de consumos~~**, eliminar **~~quintas~~**, eliminar la **~~esclavitud~~**.

El la **batalla de Alcodea** dimite el gobierno y **~~Isabel II~~** se exilia. Finalmente la **Junta de Madrid** acuerda nombrar un **gobierno provisional** de **Prim** y nombrar al **general Serrano como Regente**.

### Gobierno provisional y Constitución de 1869

#### Gobierno Provisional

Trata de restablecer el **orden** del país, aplica ciertas medidas como el **sufragio universal masculino** o **democratizar régimen liberal**. Creación de **elecciones ayuntamientos y diputaciones**  

Se funda el **prado**

Además, económicamente, se reducen los **aranceles**, se pone fin al  **~~impuesto de consumos~~**, se **crea la peseta** y con la **Ley de Bases sobre Minas**, desamortiza el subsuelo.

#### Constitución de 1869

Se caracteriza por ser **muy avanzada**, se caracteriza por el **amplio régimen de derechos y libertades**, como el derecho de asociación,  el juicio por jurado, abolición de la ~~pena de muerte~~. Además de la **descentralización administrativa**. Parlamento estable el **sufragio universal masculino**, la **confesionalidad** del estado pero con libertad religioso, la **Soberanía Nacional** y la **Monarquía Parlamentaria** sin ~~derecho de veto~~.

### La monarquía de Amadeo de Saboya (1871-1873)

<div style="color:red">Parte de este contenido no esta en el libro sino en la presentación de Rubén [El auge del republicanismo]</div>

Prim queda elegido para buscar a un rey, el elegido es **Amadeo de Saboya** o Amadeo I, era conocido porque su familia había conseguido unificar toda Italia. Su **candidatura** es **votada** en las **Cortes** y poco después muere **~~Prim~~**. 

La muerte causa que la coalición monárquico-democrática se parta en dos Partidos, el **Partido Constitucionalista de Sagasta** y el **Partido Radical de Ruiz Zorrilla** que causa una gran **inestabilidad política**. Mientras que se mantiene el **gobierno  de coalición de unionistas, progresistas y demócratas** de **Serrano**.

Durante su reinado se enfrenta a dos guerras: el **alzamiento Carlista (1872-1876)** y el conflicto de Cubo del **Grito de Yara**. Además de **insurrecciones de republicanos**  en Andalucía y Cataluña exigiendo la abolición de **~~Quintas~~** y **~~Pena de Muerte~~**,  y la extensión del **movimiento obrero** que causo la declaración de la **~~Internacional~~** ilegal.

Adicionalmente, se enfrenta a la oposición de clases populares y la **Iglesia** por la reducción del territorio de los Estados Vaticanos de la dinastía Saboya.

Por último las élites tradicionales, son agrupadas por **Cánovas del Castillo** que propone la restauración de la monarquía con **Alfonso XII**.

Todo esto causa que **~~Amadeo I~~** renuncie al trono en 1873.

### La I República (1873-1874)

#### Proclamación de la I república

Tras abdicar Amadeo I, las Cortes proclaman la **república**, el primer gobierno fue el de **Estanislao Figueras**, el cual decidió mantener la **Constitución de 1869, pero sin artículos monárquicos**. Sin embargo el gobierno de coalición se rompe.

#### Intento de República democrática y federal

Se forma un gobierno presidido por **Pi i Margall** que propone elaborar la **Constitución de 1873**, basada en la **Soberanía Popular**, **Sufragio universal masculino** **Separación de poderes**, separación iglesia estado (**aconfesionalidad**) y **descentralización** en  17 estados entre ellos Cuba y Puerto Rico.

#### Las distintas concepciones de la república

Por una parte, los **republicanos unitarios** liderados por Emilio Castelar que defendían una **república unitaria**; es decir, el poder recae sobre un único centro de poder.

Por otra parte, los **republicanos federalistas** liderados por Pi i Margal, que proponen la creación de una **república federal laica**, también proponen la reducción del **~~intervencionismo militar~~** y fin de la **~~esclavitud~~**. 

Se dividen en dos corrientes: **benévolos** implantación de la república federal **gradualmente**, desde **Cortes Constituyentes**, **desde arriba**. Mientras que los **intransigentes**, que querían acelerar los cambios desde **abajo**, van vinculados a la extensión del **anarquismo** de la Internacional (**AIT**).  Poco a poco se forman **Cantones**

#### Los problemas de la República y liquidación de la República

Se enfrentan a numerosos problemas: **insurrección Carlista** en Cataluña, Aragón y País Vasco; **insurrección Cuba**, la impaciencia de intransigentes que deriva en la proclamación de **cantones federales** que tenían gobiernos autónomos, uno de los cantones más conflictivos fue **Cartagena** (Murcia); **aislamiento internacional**, salvo Suiza y Estados Unidos ningún otro país reconoce a España como república

Ante toda esta situación **~~Pi i Margall~~** dimite por tener que utilizar las armas para acabar con la revuelta. Fue sustituido por **Salmerón** que nombra a el general Pavía y Martínez Campos, para frenar el cantonalismo, sin embargo, **dimite por el mismo motivo que su predecesor**.

**Emilio Castelar**, es nombrado presidente que plantea la **república unitaria**, mediante medidas **autoritarias** (~~Cortes~~,  decretos). Pero el pronunciamiento del general **Pavía**, apoyado por la guardia civil en contra del gobierno de Emilio Castelar, causa su dimisión.

Por último, una coalición de **unionistas** y **progresistas** dirigida por **Serrano**, aplica **medidas más autoritaristas**, como  eliminar la **~~AIT~~**, **~~ilegalizar el federalismo, ayuntamientos y diputaciones.~~** Un pronunciamiento de Martínez Campos del Manfiesto de Sandhurst, acaba con la ~~república~~ he instaura a **Alfonso XII** como monarca.



 

