# El proyecto reformista de la II República (1931-1936)

## 1933: la encrucijada republicana 

Las reformas impuestas por la coalición republicano-socialista produjo desencanto tanto por parte de la derecha como de la izquierda. Por un lado, la iglesia; el ejército y las organizaciones patronales mostraron una fuerte resistencia ante estos cambios y, por otra parte, la izquierda quedaba descontenta por la  lentitud e insuficiencia de las reformas. En añadidura el centro también quedaba disconforme con las reformas religiosas.

### Radicalización del obrerismo

La CNT vio que era el mejor momento para su proyecto revolucionario. Tuvo que hacer frente al surgimiento de dos corrientes internas: la moderada, los treintistas, dirigida por Ángel Pestaña y Juan Peiró, y la más radical, la FAI, liderada por Juan García Oliver, Buenaventura Durruti y Francisco Ascaso. La primera mostraba un cierto apoyo a la república mientras que la otra defendía la insurrección obrera para destruir el orden vigente. 

La conflictividad social llegó a su pico en 1932 cuando los revolucionarios de la CNT se unieron a los sectores más radicales del socialismo como la UGT y a la Federación de Trabajadores de la Tierra; y el Partido Comunista dirigido por José Díaz aumentó su afiliación.

### El aumento de la conflictividad social

A los problemas ya existentes (paro agrícola, reparto desigual de la tierra, escasa competitividad  y déficit de la balanza comercial) se unieron los problemas ocasionados por el Crack del 29 y el aumento del paro. Además de que la inversión privada disminuyó y la República empezó a generar desconfianza entre los empresarios industriales y los agrícolas.

Este deterioro económico incrementó la conflictividad propiciando las huelgas, insurrecciones y la ocupación de tierras. Estas revueltas solían consistir en la toma del ayuntamiento, la quema de registro de propiedad y la colectivización de la propiedad. Eran las tropas de la Guardia Civil o de la Guardia de Asalto las que ponían fin a las revueltas mediante una dura represión. Esta en ocasiones comportaba la muerte de campesinos como en el caso de Casas Viejas (1933). Las revueltas comportaron por tanto un aumento de la violencia política con la fuerza pública en los pueblos y ciudades ocasionando numerosos muertos, heridos y detenidos.

### La reorganización de la derecha

Los sectores descontentos con la trayectoria de la República se fueron organizando alrededor de los tradicionales partidos conservadores o de nuevas organizaciones de carácter fascista y autoritario. El centro-derecha se reestructuró alrededor del Partido Radical de Lerroux, que atrajo a grupos no tan opuestos a la república como a su carácter izquierdista. De igual modo la derecha monárquica, católica y conservadora se opuso a la reforma religiosa, a la reforma agraria y al Estatuto de Cataluña. 

En 1933 surgió la Confederación Española de Derechas Autónomas (CEDA) que contó rápidamente con un buen número de afiliados y con José María Gil Robles como líder. Asimismo, la monárquica Revolución Española, la Comunión Tradicionalista y grupos de inspiración fascista; JONS y Falange Española;  liderada por José Primo de Rivera, realizaron una actividad de agitación contra el peligro de una revolución bolchevique. 

Tras el fracaso del golpe de Estado de Sanjurjo en 1933 un sector militar creó la Unión Militar Española (UME), una organización clandestina de militares derechistas que tuvieron una participación activa en el golpe de Estado de 1936.

### La Crisis del gobierno de Azaña

El desgaste de la coalición republicano-socialista fue en aumento entre primavera-verano de 1933. En consecuencia de Casa Viejas Azaña fue acusado por la derecha, por emplear métodos dictatoriales y ser responsable de la matanza. Los socialistas se cuestionaron si seguir apoyando al gobierno y los Rep. radicales aprovecharon para aproximarse a la CEDA.

Cada vez fue haciéndose más visible la crisis de la coalición y su desgaste, perdiendo la confianza de las clases populares y medias. También se  vio perjudicada por las duras medidas policiales que ejercían para mantener el orden público. Bajo estas circunstancias Azaña dimitió y el presidente de la República Niceto Alcalá-Zamora nombró al radical Diego Martínez Barrio, con la finalidad de disolver cortes y convocar elecciones generales en noviembre de 1933.

### Las elecciones de 1933

El nuevo sistema electoral aprobado por las Cortes Constituyentes trataba de corregir el exceso de partidos con un sistema que favorece a los grandes partidos. Por una parte, la derecha concentró sus fuerzas y decidieron coaligarse. Los resultados de las urnas dieron el triunfo al centro-derecha. La CEDA de Gil Robles fue el gran vencedor con 115 diputados junto con el Partido Radical. Por otra parte, la izquierda se presentó desunida y, republicanos y socialistas, desunidos por la etapa anterior, presentaron candidaturas separadas. Además de la numerosa abstención de las masas por petición de la CNT, que defendía su tradicional apoliticismo revolucionario. De este modo, los partidos que habían apoyado al gobierno de Azaña no consiguieron más allá de 90 escaños de lo que iban a ser las nuevas cortes. La izquierda acusaba a la mujer de la tendencia derechista del resultado en las urnas.

## 10.4-La rectificación conservadora de la República (1934-1935)

### El gobierno radical-cedista

En el nuevo gobierno la CEDA no gobernó de forma directa sino que del partido republicano radical dirigido por Lerroux. Este se propuso a ralentizar, hasta eliminar, las reformas que se habían propuesto durante el periodo anterior:

- **Se frenó la reforma agraria** devolviendo las tierras a la nobleza, anulando la cesión de tierras mal cultivadas y concediendo libertad de contratación, suponiendo la bajada del salario de los jornaleros.
- **Se suspendió la legislación laica** y se retomó la enseñanza religiosa en las escuelas. También se aprobó un presupuesto de culto y clero y se iniciaron negociaciones para firmar un concordato con la Santa Sede.
- **Se sustituyeron algunos ayuntamientos** controlados por republicanos izq. y soci.
- **La legislación sociolaboral empezó a no ser aceptada** sobre todo en el mundo rural. Además la libertad de contrastación agravó la tendencia a la baja de jornales.
- **Ley de Amnistía** que afectó al Ejército y permitió a Sanjurjo abandonar la prisión. Este rápidamente fue a Portugal desde donde encabezaría un nuevo golpe de Estado 1936.

### El aumento de las tensiones

En 1934 a causa de la Ley de Contratos de Cultivo, que permitía a los campesinos arrendatarios de las viñas; los rabassaires; acceder a la propiedad de las tierras pagando a los propietarios unos precios marcados, el gobierno central se enfrentó a la Generalitat de Cataluña. Finalmente, el tribunal decretó su inconstitucionalidad y anuló sus efectos. El gobierno catalán no aceptó la anulación y aprobó una nueva ley idéntica. Por otro lado, el gobierno también se enfrentó al nacionalismo vasco al paralizar en las Cortes el proyecto de estatuto impulsado por el PNV.

El gobierno de carácter conservador y la obstrucción de las reformas tuvieron como consecuencia la radicalización del PSOE y de la UGT a manos de Largo Caballero. En junio de 1934, los socialistas declararon una huelga general campesina en favor de una mejora de las condiciones laborales, alcanzadas en el bienio anterior. 

Debido a la situación la CEDA reclamó una acción más fuerte y exigió participar en el gobierno, bajo la amenaza de retirar su apoyo parlamentario. Lerroux acabó otorgando tres carteras ministeriales, lo que fue interpretado por la izquierda como un acercamiento al fascismo.

### Octubre de 1934

Los socialistas declararon una huelga general revolucionaria que fracasó por la falta de cooperación y la contundente respuesta gubernamental, esto se decretó como estado de guerra. Por una parte, en Asturias el gobierno envió un ejército formado por africanistas al mando del general Franco. En consecuencia muchos dirigentes izquierdistas fueron encarcelados, como Largo Caballero, y se cerraron sindicatos y sedes. Por otra parte, en Cataluña, la Generalitat, la cual estaba enfrentada con el gobierno, proclamó el Estado Catalán de la República Federal 

Española e invitó a todas las organizaciones izquierdistas a establecerse en Barcelona. La intervención del ejército aplastó rápidamente esta rebelión y todos los responsables fueron encarcelados, e incluso Manuel Azaña que estaba allí casualmente.

### Disolución de las Cortes

Como consecuencia a la revolución la CEDA aumentó su influencia en el gobierno y se mostró partidaria de aplicar las condenas derivadas por la insurrección. También se suspendió el Estatuto de Autonomía de Cataluña, se anuló la Ley de Contratos de Cultivo y los campesinos fueron obligados a pagar las rentas en su totalidad. Se devolvieron las propiedades a los jesuitas y se nombró a Gil Robles ministro de Guerra y a Francisco Franco, jefe del Estado Mayor. Además, la CEDA presentó un proyecto de modificación de la constitución: una revisión de las autonomías, la abolición del divorcio y la imposibilidad de la expropiación de tierras.

En otoño de 1935, estalló una crisis en el gobierno: el Partido radical se vio afectado por escándalos de corrupción como el estraperlo, y de malversación de fondos, como el caso de Nombela. Estos acontecimientos agravaron las diferencias en la coalición y la visibilidad de la incapacidad de los radicales de Lerroux para gobernar. Tras esta división del centro-derecha, Gil Robles intentó que lo nombraran presidente del gobierno pero Alcalá Zamora se negó y convocó nuevas elecciones para febrero de 1936.

## El Frente Popular (febrero-julio 1936)

### Las elecciones de febrero

Como consecuencia del sistema electoral de mayorías, los partidos centro-izquierdistas se unieron en una sola candidatura: el Frente Popular. Los de derechas se agruparon en el Bloque Nacional y no admitieron a los candidatos del partido de la Falange. Portela Valladares también impulsó una candidatura de centro. Los efectos del nuevo sistema electoral convirtieron una pequeña diferencia en número de votos en una gran victoria en escaños dando la victoria al Frente Popular (diferencia de 46,48%-47,03% de votos) lo que se tradujo en una España polarizada. Este resultado tan ajustado se tradujo en 285 diputados para el Frente Popular (republicanos, PSOE y PCE) y solo 166 diputados para la derecha.

### Los problemas del Frente Popular

- El nuevo gobierno quedó formado por republicanos mientras que los partidos coalicionados prometieron apoyo parlamentario. Manuel Azaña fue nombrado presidente de república y Santiago Casares Quiroga presidente de gobierno. Su actuación  se basó en realizar lo pactado en la coalición.  Así se decretó una amnistía que supuso excarcelar a múltiples presos políticos, y se obligó a las empresas a readmitir a las personas despedidas  por lo ocurrido en 1934. El Gobierno de la Generalitat fue restituido y se restableció el Estatuto de Autonomía de Cataluña. Se empezó a negociar el estatuto P.Vasco.

- Con la perspectiva de cambio, los izquierdistas iniciaron movilizaciones populares. Los anarquistas proponían acciones revolucionarias y algunos socialistas proponían soluciones más radicales. En las ciudades se convocaron huelgas y, en el campo, los jornaleros comenzaron a hacer ocupaciones de las tierras para su reparto.

- Buena parte de la derecha depositó sus esperanzas en un golpe de fuerza que acabase con el Frente Popular. Los derechistas volvieron a oponerse a las reformas: algunos empresarios tuvieron que cerrar fábricas, la iglesia volvió a lanzar campañas contra la república y también hubo oposición por parte de los propietarios de las tierras. La Falange Española fomentó un clima de crispación política fomentando acciones violentas contra los líderes izquierdistas que fueron respondidas del mismo modo por parte de la izq.

### De la conspiración al golpe de estado

Este clima de enfrentamientos favoreció a los partidarios del golpe de estado y a pesar de la decisión del gobierno de trasladar a los más sospechosos lejos de Madrid, la conspiración se extendió gracias a la Unión Militar Española cuyo papel resultó fundamental. La misma noche de las elecciones de febrero Franco intentó declarar estado de guerra y en marzo un grupo de generales acordó “un alzamiento que restableciese el orden”. En sus inicios la conspiración tuvo poca fuerza y mala organización hasta que comenzó a ser dirigida por Emilio Mola. Su plan consistía en un pronunciamiento militar simultáneo, siendo claves en Madrid y Barcelona, con protagonismo especial del ejército de África, al mando de Franco.

Con el general Mola y Sanjurjo, que debería ponerse al frente de una junta militar cuando la sublevación estallase, los conspiradores atrajeron incluso a generales con fama de republicanos. También consiguieron respaldo económico y establecieron contacto con la Italia fascista y la Alemania Nazi. Además, contaban con el apoyo de las fuerzas políticas de la derecha(cedistas, monárquicos, carlistas y falangistas). Finalmente, el momento elegido para el golpe fue el asesinato de Calvo Sotelo en respuesta al homicio de Castillo el 18 de julio de 1936.