# La transformación social del siglo XIX
## La configuración de la sociedad de clases

### De súbditos a ciudadanos

Con el triunfo del **liberalismo**, los ~~súbditos~~ pasan a ser **ciudadanos** que gozan de **igualdad jurídica** por la abolición de los ~~estamentos~~. Sin embargo, el **sufragio censatario** causa que el proletariado no pueda participar en la política. Además, aparecen las **diferencias de clases** por la riqueza

### La reordenación de los estamentos privilegiados

Con la abolición de los ~~privilegios~~, por una parte, la **alta y media nobleza** mantienen su **importancia social, económica y política**, ya que todavía conservan **patrimonios** agrarios que les dotan de **poder económico**. Mientras que por otra parte, la nobleza baja representada por los **hidalgos**, con la perdida de los ~~privilegios~~ sufren **deterioro económico** y se acaban fusionando con la clase media.

Paralelamente, la **iglesia** con las **desamortizaciones** (~~conventos~~) y la supresión del **~~diezmo~~**, pierde **poder económico ↓↓**. Aunque lo recuperan con el presupuesto público al **culto y clero**, además, en el ámbito social domina la enseñanza.

### La sociedad de clases

Los ~~estamentos~~ fueron sustituidos por las **clase sociales**, propias de un régimen libera-capitalista

Por una parte, las **clases dirigentes**, representaban la nueva élite social, estaba conformada por la alta burguesía, el alto funcionariado, la nobleza... Como consecuencia del sufragio censatario ejercían el **poder político**

Por otra parte, las **clases populares** que no ejercían el poder político estaban conformadas por el campesinado y el **proletariado**. Suponían la mayor parte de la población.

Alternativamente, aparece la **clase media**, que está entre las dos anteriores, supone un porcentaje ínfimo de la población aunque a medida que pasa el tiempo aumentará su tamaño

### Un nuevo tipo de conflicto social

El **capitalismo** causa **desigualdades sociales**, por eso, en **España**  y en el resto de países de Europa aparece el **movimiento obrero**. 

En primer lugar, **luchan contra las máquinas** y después por la mejora de las condiciones de trabajo. Para ello utilizan nuevas técnicas más eficaces como la **huelga** y las **asociaciones sindicales.**

Además aparecen movimientos como el: **socialismo**, **anarquismo**, y **republicanismo**.

***

## Los nuevos grupos dirigentes

### Élite económica y bloque del poder

Se produce una **simbiosis entre aristocracia y burguesía**. Por una parte, la aristocracia mantenía **tierras** y  los **títulos nobiliarios**. Además de una **gran influencia**. Mientras que la **burguesía** que tenia **capital** y tenía mucho interés en los **títulos nobiliarios**. Por ello durante el reinado de Isabel (1844-1868) creo más de **400 títulos**.

Como consecuencia de esta unión aparece una nueva **oligarquía** que con el **poder económico** impone las **formas socio-culturales**, que además con el sufragio censatario del **moderantismo**, **monopoliza** el **poder**.

### La alta burguesía

Vinculada con **ferrocarril**, **banca e inversiones**, **comercio**. Aunque la gran mayoría de ella estaba más interesada en inversiones de tierras que en industria, por lo que con las **desamortizaciones** aumentan el patrimonio y pasan a convertirse en **rentistas**

**Madrid** pasa a ser el centro de negocios, aunque también hay numerosos burgueses asentados en **País Vasco**, **Cataluña** y **Asturias**


### Burguesía Industrial

Sobre todo burgueses de la industria **textil catalana** y **siderúrgica vasca**, durante todo el tipo tratará de conseguir una política arancelaria **proteccionista** 

### Las clases medias

Menos del **15%** de la población. Se trata de **pequeños propietarios de tierras**, **oficios de carácter liberal** (médicos, abogados, notarios...), **funcionarios** y **militares de rango medio**. La gran mayoría de ellos no podían **~~votar~~**. A pesar de esto, esta clase defiende la **democracia, republicanismo, orden y  propiedad privada**

***
## Las Clases Populares

### El campesinado

Podemos dividir al campesinado en tres grupo: **pequeños propietarios**, **arrendatarios** y **jornaleros**. Los primeros, con la eliminación del ~~régimen señorial~~ y las desamortizaciones han **adquirido tierras**, aunque son muy pocos los de esta clase. Los segundos **alquilan tierras**, que podían pasar de generación en generación. Finalmente, los **jornaleros**, eran la **gran inmensa mayoría**, estos trabajaban por **escasos jornales diariamente**.

El panorama agrícola del siglo XIX se ve marcado por el **hambre de tierras** y la **problemática del jornalero**. Además, también dependen de los **caciques**.
### Artesanos y oficios urbanos

A pesar de la abolición de los **~~gremios~~** (1830), el sector de los **artesanos** (carpinteros, herreros...) sigue teniendo un peso importante durante el resto del siglo XIX.

Mientras tanto en la **ciudad** aparecen **oficios** relacionados con los **servicios**: funcionariado bajo, faroleros, serenos, dependientes...

Además de las **clases más humildes**, aparecen lavanderas, planchadoras, amas de casa, criadoras... que sirven a la burguesía.
### El proletariado industrial

Aunque a **mitad** del siglo **XIX** es muy reducido, solamente presente en el sector textil de **Cataluña**, con el desarrollo de la **minería y la metalurgia** también aparecerán en **País Vasco y Asturias**. 

El proletariado industrial se caracteriza por padecer **condiciones laborales durísimas**: jornadas largas, salarios bajos, lugares de trabajo con malas condiciones ambientales (iluminación, ruidosos, húmedos) y poco seguros. Además tanto **mujeres**, como **hombres** **y niños trabajaban en las fábricas**.

Por último, solían vivir en **suburbios industriales** en barrios deplorables y miserables de la ciudad, carecían de servicios y las enfermedades se propagaban muy rápido.

### Los grupos marginados

Eran aquellos que **no podían trabajar:** mendigos, huérfanos, viudas, minusválidos, personas con problemas psicológicos...No recibían ningún tipo de **asistencia social** del estado. 

***

## Los orígenes del movimiento obrero

### La toma de conciencia obrera

El movimiento **obrero** aparece durante la **industrialización** y en el inicio del **capitalismo** para **luchar** por unas mejores **condiciones de vida o laborales**, además de la **igualdad económica**. Ya que la clase obrera padecía **condiciones precarias**. 

### El ludismo: la lucha contra la máquina

A partir de **1820**, al igual que con la aparición de las máquinas, aparece el **ludismo** para luchar en contra de las **máquinas** las cuales son las **culpables** de la **pérdida de puestos**. Destacan dos incidentes, el incendio en una fábrica de Alcoy y el de la fábrica **Bonaplata** en Barcelona.

Sin embargo, los obreros se dieron cuenta que el problema no residía en el uso de las máquinas, sino en las **condiciones del proletariado**; en Cataluña aparece el primer documento que se oponía a la decisión de alargar las piezas sin aumentar el salario.

### Las primeras sociedades obreras 

Aparecen las **Sociedades de Protección Mutua** donde los obreros pagaban una cuota para pagar el jornal en caso de tener una enfermedad, despido o huelgas (las cuales están prohibidas).

### La expansión del obrerismo

Reclamaban **subida de salarios y reducción horaria** además de **la libertad de asociación**, durante la mitad del siglo XIX aumenta considerablemente el número de huelgas. Hasta que en en 1855, durante el Bienio Progresista (1854-1856) nos encontramos con la **primera huelga general** en **Barcelona**.

### La revueltas agrarias

Suponen un **grave problema social**. Esta presente en toda España aunque especialmente en **Andalucía**, donde hay constantes insurrecciones, **toma de tierras** para repartir entre los jornaleros y **quema de registros** notariales de la propiedad. Además, la situación empeora con la **desamortización de Madoz** durante el Bienio Progresista (1844-1854), la cual elimina las ~~**tierras comunales**~~ .

***

## Las primeras ideologías obreras y el internacionalismo

### Los precursores: republicanismo y utopismo

Con el **sufragio universal masculino** los obreros votaron a los **republicanos** los cuales, por la falta de respaldo político no cumplieron con las reivindicaciones de los obreros.

Como consecuencia de esto, aparecen los utópicos que **denuncian** las **injusticias sociales** creadas por el capitalismo industrial. Encontramos distintos precursores, destacan Owen con el cooperativismo y Fourier que propone los **Falanasterios**. En ellos los obreros cooperaban por la producción.

### La llegada de la Internacional

En Londres aparece la **Asociación Internacional de Trabajadores (AIT)** conformada principalmente por dos ideologías, los **socialistas** de Karl Marx y los **anarquistas** de Bakunin.

Los primeros sostenían que mediante la revolución de la clase obrera tenía que construir un nuevo Estado obrero **(dictadura del proletariado)**. Mientras que los segundos estaban en contra de los partidos políticos y abogaban por la ~~Abolición del Estado~~. 

Las idas de la AIT llegan a España a través del anarquista Fanelli en la Revolución de 1868

### La expansión de la Federación Regional Española (FRE)

Está mantenía una ideología anarquista, optaron por el **apoliticismo** y la **acción directa**. Era la representación de la **AIT** dentro de España y su primer congreso fue en Barcelona

### La crisis y escisión en la FRE

El declive comienza tras el **levantamiento cantonalista en la primera república**. Además, en la **Comuna de París** muchos países acordaron la prohibición de la AIT

Por una parte, por impulso del **yerno de Marx** se crea una **línea marxista dentro de la FRE**, sin embargo esto produce una **escisión** que causa la aparición de la **Agrupación Socialista Madrileña** después se acabaría transformando en el PSOE.

Por otra parte, el ya mencionado **levantamiento cantonal** y la **huelga general** de **Alcoy**, motivó a los conservadores a estar en contra de la **FRE**

Finalmente en el inicio de la **Restauración**, se prohíbe la **~~AIT~~** y por tanto la **FRE** se disuelve.
