# La Consolidación de la democracia

## La transición (ruptura pactada o reforma)
### La nueva monarquía de Juan Carlos I

La ausencia de representantes de gobiernos democráticos en el funeral de Franco dio a ver el gran aislamiento internacional del régimen. Juan Carlos continuó como jefe del estado lo que generó incertidumbre. La continuación inmovilista del franquismo tuvo gran apoyo sin embargo el futuro de la monarquía inspiraba más un proyecto reformista. El gobierno de Arias Navarro propuso el espíritu del 12 de febrero que proponía una reforma de las leyes franquistas. Esto disgustó a los inmovilistas y también fue rechazado por la oposición ya que esta reforma no comportaba una democracia.

### La movilización social y política

Aumentaron las movilizaciones, huelgas y manifestaciones en contra de la voluntad reformista. También se produjo un aumento de la conflictividad obrera, estudiantil, vecinal y feminista; y se empezaron a ocupar las calles. La oposición política<<de forma clandestina>> (la junta y la plataforma de convergencia Democrática) utilizaron la conflictividad de la calle para impulsar la democracia. La elevada represión que se generó chocó con el reformismo de Arias lo que dio a ver su incapacidad para atender las demandas sociales y atraer a la oposición.

### La monarquía toma la iniciativa: cambio de gobierno → Alfonso Suárez

Juan Carlos I forzó la dimisión de Arias Navarro y proclamó la formación de un nuevo gobierno presidido por Alfonso Suarez. El fracaso de Arias supuso el fracaso de la continuidad del franquismo y supuso la radicalización de los inmovilistas → el búnker. El nuevo proclamó una amnistía a los presos antifranquistas y centró su objetivo en la Ley de Reforma Política. Esta reconocía derechos y libertades fundamentales, promovía cortes bicamerales,  preveía  elecciones  y  otorgaba  a  las  cortes  la  reforma  de  las  leyes fundamentales con el objetivo de crear una nueva legalidad constitucional.

### La Ley de Reforma Político 

Esta fue la ley que se cargó la dictadura, Suarez consiguió que esta fuese aprobada en las mismas cortes franquistas ya que garantizó a los procuradores que no tendrían responsabilidades políticas y que no legalizaría el PCE. Esta ley se acabó consolidando con un referéndum el cual tuvo como resultado, por una parte, la oposición que se movió entre el “Sí” y la abstención, y por otra parte, el búnker que se inclinó al “no”. El resultado final fue el “Sí”. El gobierno negoció las condiciones para las elecciones democráticas desarticulando algunas instituciones franquistas y concediendo libertad de prensa, legalidad de los partidos políticos y derecho de huelga. Este liberalismo se vio alterado por la violencia ejercida por la ETA y el GRAPO que pretendían sabotear el proceso(asesinato de atocha y de abogados de CCOO). Para impulsar las elecciones se  aprobó una ley electoral y se acabó legalizando el PCE. La izquierda se organizó alrededor del PCE/PSOE, en la derecha apareció Alianza Popular como “heredera del franquismo”y surgió la Unión de Centro Democrático.Se legalizaron +100 partidos.

### Elecciones Generales de 1977

Estas se celebraron con normalidad, tuvo una participación muy elevada y dio como resultado, a pesar de haber + de 100 partidos legalizados, una clara tendencia bipartidista. El primer lugar lo obtuvo la UCD y en segundo el PSOE. A pesar de que el gobierno de Suarez no consiguió la mayoría absoluta pudo formar el primer gobierno democratico desde la guerra civil. Para la elaboración de una nueva constitución se llevó a cabo una política de consenso que permitió la aprobación de un conjunto de leyes y medidas: amnistía, pactos de la moncloa y reforma fiscal. Ley de amnistía

Permitió la excarcelación de presos, terroristas(FRAP, ETA, GRAPO), políticos y funcionarios. Esta fue la primera ley aprobada por mayoría y tuvo una fuerte carga simbólica de lucha antifranquista. También fueron excarcelados aquellos cuya ideología opuesta al régimen les había pasado factura debido a la represión ejercida por el régimen franquista.

### Contexto: Crisis económica

El contexto de gran crisis económica internacional ocasionada por el aumento del precio del petróleo de 1973 afectó en gran medida a la economía española: se disminuyeron las exportaciones, inversiones y el turismo (entrada de divisas). También se produjo el retorno de emigrantes lo que supuso la disminución de las remesas. La crisis supuso el cierre de muchas empresas y el aumento de la inflación, lo que provocó una huelga de capitales que puso en tensión a la democracia. Debido a esto el país alcanzó un déficit económico importante pero no entró en bancarrota. Todo esto supuso el aumento de la conflictividad laboral y una gran inestabilidad política. Por lo que Suárez buscó un amplio consenso político y social el cual fue concretado en los pactos de la moncloa.

### Los Pactos de la Moncloa

En esta se llevaron a cabo dos acuerdos: la Reforma fiscal de la economía y un programa de actuación jurídica y política. La reforma fiscal tuvo como objetivo reducir la inflación por lo que se tomaron medidas como la devaluación de la peseta, la limitación de los salarios, el despido libre y una reforma de la hacienda con el IRPF con el objetivo de recaudar el dinero necesario para la construcción del estado de bienestar y reformar la seguridad social. El programa de actuación adoptó medida políticas como la libertad de expresión, reunión o asociación; la creación del delito por tortura y el aumento de los derechos de las muejeres. Estos tuvieron una eficacia limitada ya que se incumplieron las medidas y a que se inició la II crisis del petróleo en 1979.


## Bases institucionales de la nueva democracia

### Constitución de 1978

La redacción de esta nueva constitución fue el resultado de un amplio consenso político, tuvo la partición de los representantes de todos los partidos menos del PNV. Los partidos siempre buscaron el acuerdo entre ellos y tuvieron debates como el concepto de nacionalidad, la educación pública y privada, la libertad de empresa y la no confesionalidad Católica del Estado. Se definió a España como un Estado social y democrático de Derecho, se organizó como una monarquía parlamentaria; por lo que la corona pasó a una función representativa, se proclamó una separación de los poderes y se instauró el Tribunal Constitucional como autoridad suprema. Se estableció la soberanía nacional y se reconoció el derecho al territorio de las autonomías. Se produjo un aumento de los derechospolíticos  y sociales y se reforzó la no discriminación por razó nde edad, sexo, raza o religión, y se fijó el derecho al voto universal a los mayores de 18 años. La constitución fue aceptada por ambos extremos y se avaló en un referéndum.

### El estado de las autonomías

Tras las elecciones se restablecieron la Generalitat de Cataluña, se negoció la creación del consejo Vasco y se instauró la primera Xunta en Galicia. Con el reconocimiento del derecho a la autonomía recogido en la constitución, se instauró un sistema de descentralización→ creación de las Comunidades Autónomas. A cada una se le dotaría de estatutos de autonomía y de competencias a nivel legislativo, ejecutivo y judicial. Para acceder a la autonomía se establecieron dos procedimientos: el artículo 151, el cual era un método más rápido pero solo podía ser ejercido por los tradicionales nacionalismos, y el artículo 143, el cual era un proceso más lento.

### Los ayuntamientos democráticos

Los ayuntamientos franquistas continuaron hasta las elecciones de 1979. Este era el último paso para la elaboración del sistema democrático. Estos deberían de estar formados por concejales electos por sufragio universal y los alcaldes serían elegidos por los concejales o los vecinos.

### El segundo gobierno de Suárez

Las nuevas elecciones de 1979 tuvieron un resultado similar. La vencedora fue la UCD dirigida por Suárez, pero seguida del PSOE que  comenzaba a ganar influencia. El nuevo gobierno de Suárez debía convocar elecciones municipales, desarrollar las autonomías, afrontar la crisis económica y frenar la escalada del terrorismo: La celebración de las elecciones municipales no fue favorable para el gobierno debido a que el pacto PSOE-PCE dotó a la izquierda de más capitales de provincia que las que consiguieron UCD. Esto supuso que el gobierno empezará a debilitarse. Además se provocó un aumento de las tensiones en Andalucía ya que la junta consiguió el acceso a las autonomías mediante el artículo 151 en contra de la voluntad del  gobierno. En 1980 el PSOE presentó una moción de censura, la cual ganó Suarez. Sin embargo poco después presentó su dimisión por la problemática y a que su liderazgo fue cuestionado.

### Concertación social

La crisis derivada del tardofranquismo había afectado al país, esto supuso el aumento de la crisis económica → aumento del desempleo y de la inflación. Para abordar la crisis se desarrolló una política de concertación social con la formación de acuerdos con empresas, UGT, CCOO para la moderación laboral. Esta concertación supuso aceptar la moderación salarial. Por otro lado, el aumento de las coberturas sociales(paro/pensión) supuso la disminución de la conflictividad laboral. También se  permitió la elaboración del Estatuto de los Trabajadores 1980.

## Golpe de Estado del 23F

En 1978 se desarticuló un intento de golpe de estado (operación Galaxia), pero hizo resurgir las tensiones. El intento más relevante fue el del 23F durante la investidura de Calvo Sotelo como sucesor de Suárez. Un grupo de guardias civiles armados irrumpió en el Congreso de los diputados al mando de Antonio Tejero. Paralelamente, MIlans del Bosch se levantó en Valencia.. Su objetivo era paralizar el proceso democrático y otorgar al ejército un papel relevante en la política. Sin embargo este no tuvo éxito aunque no se supo muy bien que pasó ya que se cortó la emisión en vivo a mitad. Al día siguiente se dio lugar la comparecencia del rey donde daba apoyo al régimen constitucional, vestido de militar y dando su postura en contra del golpe.

### La Crisis de la UCD

Tras el intento del golpe de Estado, Calvo Sotelo no consiguió forjar un liderazgo en la UCD, esto se vió acentuado con su decisión de pedir el acceso a la OTAN. Su acción más destacada fue la aprobación de la LOAPA que limitó la atribución de las autonomías. Finalmente, Calvo Sotelo no consiguió frenar la autodestrucción de la UCD y Suárez abandonó el partido creando la CDS (Centro Democrático y Social). Calvo Sotelo disolvió contres y convocó elecciones.

## La imposición del bipartidismo

### Inicio gobierno de Felipe Gonzalez

En las elecciones de 1982 el PSOE obtuvo una mayoría absoluta y la AP se configuró como la mayor oposición (bipartidismo)(El PCE casi desaparece del mapa electoral). Felipe gonzalez formó un gobierno socialista y se mantuvo en el poder durante cuatro legislaturas seguidas con mayoría absoluta en las primeras tres y en la cuarta con ayuda de los nacionalistas.

### Reformas y moderación

La reforma del ejército para acabar con la autonomía militar fue una de sus prioridades. Se impuso una gran reducción de los mandos y también se renovó el armamento. Esta reforma se impulsó con la entrada en la OTAN de 1986 tras su referéndum. La segunda prioridad fue la impulsación de reformas económicas para acabar con la inflación y el desempleo, impulsando un estado de bienestar. Se impulsaron leyes educativas (logse), sanitarias, y reformas del sistema de pensiones. Se reformó la Universidad, se democratizaron los centros escolares y se configuró el sistema escolar obligatorio y gratuito para los mayores de 16 años. También se impulsó la asistencia sanitaria y sanidad fratuita con el desarrollo del Sistema Nacional de Salud, se desarrolló la libertad sindical y la no penalización del aborto.

### Crecimiento económico e integración en la CEE (Comunidad Económica Europea)

Con la integración de la (CEE) se inició una etapa de expansión económica, Esta exigió medidas contra la inflación y el déficit público, y la reconversión de la banca. También demandó afrontar el cambio  industrial  suponiendo  el  cierre  de  empresas  que  ya  no  eran  eficientes  y  su reestructuración(química, metalúrgica, naval, ...). Estas demandas se intensificarían con la entrada en la zona euro y desaparición de la peseta en 2002. El Acta Única Europea 1986 supuso la creación de un espacio sin fronteras de libre circulación, el espacio Schengen. El coste social fue muy elevado por la gran cantidad de despidos y contención de los salarios por lo que las medidas fueron insuficientes suponiendo así una huelga general obrera 1988. Esto sirvió para aumentar la protección de los parados y del gasto social. En la última candidatura se frenó el gasto público y se inició la privatización de grandes empresas públicas.

### Acción Política

El despliegue de las autonomías supuso el aumento de las tensiones entre los nacionalismo históricos que buscaban un mayor autogobierno, mientras que los otros buscaban su equiparación con estos. Esto supuso un gran nivel de descentralización. El terrrorismo de la ETA fue el principal problema político. El gobierno impulsó acciones que consiguieron debilitar a la ETA como la cooperación con Francia el Pacto de Ajuria Enea y la represión. El desgaste del PSOE que ya era notable por la crisis, aumento con la difusión de casos de corrupción como el caso de Luís Roldán(director de la guardia civil que se quedó con el dinero destinado a los huerfanos por culpa de ETA) y de metodos ilegales de lucha contra el terrorismo. Por otro lado el Partido Popular constituido a partir de la AP obtuvo buenos resultados en las elecciones de 1993 suponiendo una fuerte oposición para el gobierno.


