Aquí tienes el texto revisado con correcciones ortográficas y divisiones de párrafos donde es necesario:

---

# Preguntas Transversales (Pregunta 5)

En la PAU de la Comunidad Valenciana, la pregunta 5 (antiguamente llamada 4b), se le conoce popularmente como la *pregunta de la excelencia* o *pregunta transversal*. A diferencia de la pregunta 4 donde se pregunta por un apartado en concreto (por ejemplo: el Trienio Liberal), en la pregunta 5 el alumno tiene que proporcionar ~~a~~ una respuesta entrelazando conocimiento de todo el siglo. No hay un listado de todas las posibles preguntas transversales, ~~sin embargo a contiuación se encuentran las más relevantes, complejas o frecuentes.~~ pero a continuación se presentan las más relevantes, complejas o frecuentes.

## Carlismo

En 1833, por influencia de su esposa María Cristina, Fernando VII promulga la Pragmática Sanción ~~que~~ abol~~e~~ía la Ley Sálica. Esta ~~había sido instaurada por~~ Ley, instaurada por Felipe V, impedía a las mujeres heredar el trono Español; con su abolición, Carlos María Isidro (hermano de Fernando VII) deja de ser el heredero ~~al~~ del trono y pasa a serlo Isabel II (hija de Fernando VII).

Este suceso desencadena la división ideológica entre carlistas e isabelinos. Los carlistas sostienen que Carlos María Isidro y su descendencia son los legítimos herederos del trono Español, manteniendo una ideología absolutista. Su lema era: "Dios, Patria, Rey/Fueros". Por contraparte, los isabelinos o cristinos apoyaban a Isabel II y mantenían una ideología liberal.

La primera guerra Carlista se inicia en 1833 con la muerte de Fernando VII. A partir de ahí, María Cristina es nombrada regente de Isabel, mientras que Carlos María Isidro publica un documento (manifiesto de los Abrantes) donde se autoproclama rey de España. Como se ha mencionado antes, los partidarios del absolutismo se agrupan en torno a Carlos María Isidro (nobleza agraria, bajo clero y parte del campesinado), que instaura la zona carlista por el Maestrazgo, Cataluña, Aragón, Navarra y Euskadi; adicionalmente, reciben el apoyo internacional de otros países absolutistas como Prusia y Rusia. Mientras que los isabelinos o cristinos tienen el apoyo de la alta nobleza, la alta jerarquía eclesiástica y de los liberales que veían la posibilidad de establecer un régimen liberal con el apoyo de María Cristina; contaban con apoyo internacional de Francia y Gran Bretaña.

Durante la primera parte de la guerra, la ofensiva fue claramente superior, hasta que con la muerte del general carlista Zumalacárregui, el Carlismo se divide en dos corrientes: los transaccionistas y los intransigentes. Los primeros querían llegar a un acuerdo pacífico con los isabelinos, mientras que los segundos deseaban continuar con la guerra. Finalmente, la ofensiva de Espartero fuerza a que en 1839 se firme el Convenio de Vergara, que reinstauraba los fueros en País Vasco y Navarra, los cuales el gobierno liberal de María Cristina había abolido previamente; puso fin a la guerra en 1840.

La segunda guerra Carlista o "Guerra dels Matiners" (1846-1849) más que una guerra, se trata de una insurrección centrada en la zona de los Pirineos. Se origina cuando los intentos de casar a Isabel II con el hijo de Carlos María Isidro son frustrados. Al final, Isabel II se casa con Francisco de Asís.

La tercera guerra Carlista (1872-1876) se inicia en el Sexenio Democrático (1868-1874), ya que ante la ausencia de la figura del monarca, el Carlismo ve su oportunidad para heredar el trono. Sin embargo, la llegada de Amadeo I provoca una insurrección Carlista en contra del nuevo monarca. El conflicto acaba en 1874 cuando Alfonso XII (hijo de Isabel II) es coronado, mientras que los generales Martínez Campos y Primo de Rivera derrotan a los militares carlistas de Cataluña, Navarra y País Vasco; se abolieron los fueros y se instauró un sistema de *conciertos económicos*.

Estas son hasta la fecha todas las guerras carlistas que ha habido.

## Constituciones

### Planteamiento

Las constituciones se pueden preguntar de varias formas. Se puede pedir que se expliquen todos o algunos de los aspectos de las constituciones (sufragio, sistema de gobierno...) o simplemente se puede pedir que compares 2.

### Respuesta

{Orden: Separación de Poderes, Soberanía x, tipo de gobierno (+ cámaras), sufragio, confesionalidad y otros}

Una constitución es la carta magna de un estado que establece el marco legislativo del país, ya que todas las demás dependen de ella. Establece características del estado como la separación de poderes, la soberanía, la forma de gobierno, el sufragio y los derechos, libertades y deberes de los ciudadanos, entre otras cosas.

Durante el siglo XIX ha habido muchas constituciones. A continuación, expondremos brevemente cada una de ellas en orden cronológico.

En primer lugar, la Constitución de 1812 (también llamada "la Pepa") fue promulgada por las Cortes de Cádiz durante la Guerra de Independencia (1808-1814). Se trata de una constitución de carácter progresista. Establece la separación de poderes, la soberanía nacional, cortes unicamerales, el sufragio universal masculino indirecto para los mayores de 25 años, establece la confesionalidad, crea los derechos, deberes y libertades de los ciudadanos (libertad de imprenta y pensamiento, derecho de veto), funda la Milicia Nacional y promulga una desamortización. A la vez que abole los privilegios como la mesta, los gremios, el diezmo y los mayorazgos; también acaba con el régimen señorial.

En segundo lugar, la Constitución de 1837 fue promulgada por los gobiernos de Calatrava y Mendizábal, durante la regencia de María Cristina (1833-1840), tiene carácter progresista. Destaca por su brevedad ya que estaba pensada para que gobiernos posteriores regularan ciertos aspectos con leyes orgánicas. Establece la separación de poderes, la soberanía nacional, la monarquía parlamentaria bicameral (aparición del Senado), sufragio censatario y la confesionalidad; además a nivel de derechos y libertades mantiene el derecho de veto y añade el jurado para delitos de imprenta.

En tercer lugar, la Constitución de 1845, sancionada por Isabel II durante la Década Moderada (1845-1854), tiene ideología moderada. Establece la separación de poderes, la soberanía nacional, la monarquía parlamentaria bicameral, el sufragio censatario, la confesionalidad del estado y reduce los derechos y libertades de los ciudadanos; por ejemplo, el derecho de jurado por delitos de imprenta se restringe.

En cuarto lugar, cabe mencionar la Constitución "Non Nata" de 1856, se dice que es "Non Nata" porque no llegó a ser sancionada por Isabel II, se redacta durante el Bienio Progresista (1854-1856).

En quinto lugar, la Constitución de 1869 fue promulgada durante el Sexenio Democrático (1868-1874), tiene carácter progresista. Establece la separación de poderes, la soberanía nacional, la monarquía parlamentaria bicameral, sufragio universal masculino, la confesionalidad del estado pero con libertad religiosa, un amplio catálogo de derechos y libertades (como la libertad de expresión, reunión y asociación) y descentraliza la administración. Mientras que abole la pena de muerte, la esclavitud y el derecho de veto.

En sexto lugar, el proyecto de Constitución de 1873, que no se llegó a promulgar durante la I República (1873-1874), hubiera establecido un régimen Republicano-Federalista.

En séptimo lugar, la Constitución de 1876, promulgada en el inicio del reinado de Alfonso XII (1874-1885), sostiene un carácter conservador. Establece la separación de poderes, soberanía compartida entre el monarca y las cortes bicamerales, el sufragio censatario o universal masculino (según el gobierno), la confesionalidad pero con tolerancia religiosa y el centralismo. Además, los derechos y libertades varían en función del gobierno, aunque tendieron a restringirlos.

### Tabla Resumen

|                       | 1812                                                           | 1837                                   | 1845                          | ~~1856~~ | 1869                                             | ~~1873~~ | 1876                                                       |
| --------------------- | -------------------------------------------------------------- | -------------------------------------- | ----------------------------- | -------- | ------------------------------------------------ | -------- | ---------------------------------------------------------- |
| Ideología             | Progresista                                                    | Progresista                            | Moderada                      |          | Progresista                                      |          | Conservadora                                               |
| Separación de poderes | Sí                                                             | Sí                                     |                               |          | Sí                                               |          | Sí                                                         |
| Soberanía             | Nacional                                                       | Nacional                               | Nacional                      |          | Nacional                                         |          | Compartida                                                 |
| Tipo de gobierno      | ø                                                              | Mon. Parl.                             | Mon. Par.                     |          | Mon. Par.                                        |          | ø                                                          |
| Cámaras               | Uni-                                                           | Bi-                                    | Bi-                           |          | Bi-                                              |          | Bi-                                                        |
| Sufragio              | Universal<br>♂ indirecto                                       | Cen.                                   | Cen.                          |          | Universal<br>♂.                                  |          | Cen / Universal<br>♂                                       |
| Confesiona-lidad      | Confe.                                                         | Confe.                                 | Confe.                        |          | Confe. pero libertad religiosa                   |          | Confe. pero libertad religiosa                             |
| Derechos y libertades | Imprenta, pensa-miento y veto                                  | Anterior + jurado por delitos imprenta | - jurado por delitos imprenta |          | Anterior + libertad expre, reunión y asocia-ción |          | Varían en función del gobierno aunque tienden a restringir |
| Elimina               | ~~mesta, gremios, diezmo, mayor-azgos y regimen señorail~~<br> |                                        |                               |          | ~~pena muerte, esclavi-tud y derecho de veto~~   |          |                                                            |
| Otros                 | Desamor-tización y funda Milicia Nacional                      |                                        |                               |          |                                                  |          |                                                            |

## Desamortizaciones

### Respuesta

Las desamortizaciones son estrategias económicas que consisten en expropiar tierras sin uso o en manos muertas para ponerlas a la venta. Con su venta, se llenan las arcas del estado mientras se fomenta la producción agraria. Durante el siglo XIX hubo 7 desamortizaciones, todas vinculadas a momentos de crisis.

La primera desamortización fue propuesta por Godoy en 1807 para paliar la crisis económica producida por la ruptura del comercio triangular y la economía mercantilista, causada a su vez por la batalla de Trafalgar donde se perdió gran parte de la flota Española. Tiene carácter eclesiástico.

La segunda desamortización fue propuesta, junto con otras medidas, dentro del Estatuto de Bayona promulgado por José I en 1808, tras las abdicaciones de Carlos IV y Fernando VII. Tiene carácter eclesiástico.

La tercera desamortización fue iniciada por las Cortes de Cádiz. Su intención era recaudar dinero para amortizar la deuda pública generada por la Guerra de la Independencia (1808-1814). También de carácter eclesiástico.

La cuarta desamortización fue propuesta por el gobierno liberal instaurado en el Trienio Liberal (1820-1823) tras el pronunciamiento de Riego. Su objetivo era vender las tierras de la iglesia para recaudar recursos para la hacienda y limitar el poder de la iglesia.

La quinta desamortización fue propuesta por Mendizábal, presidente del gobierno o ministro de economía, de ideología liberal. El objetivo de esta desamortización eclesiástica era obtener dinero para financiar el ejército liberal que combatía en la primera guerra Carlista (1833-1840), recaudar dinero para la hacienda y crear una clase de propietarios defensores del régimen liberal. Aparte de expropiar tierras, disolvió ciertas órdenes religiosas.

La sexta desamortización fue propuesta por Madoz durante el Bienio Progresista (1845-1856). A diferencia de todas las anteriores, además de ser eclesiástica, también tiene carácter civil; ya que desamortiza todas las tierras comunales. Esto supuso un duro golpe para los sectores más pobres del campesinado, ya que al no poder cultivar ahí, muchos tuvieron que emigrar a la ciudad.

La última desamortización (7ª) fue la del subsuelo. Fue propuesta en la "Ley de Bases sobre Minas" del gobierno provisional de Prim, prácticamente al inicio del Sexenio Democrático (1868-1874).

### Tabla Resumen
| Nº  | Nombre                                          | Tipo                 | Objetivo                                                                                                               |
| --- | ----------------------------------------------- | -------------------- | ---------------------------------------------------------------------------------------------------------------------- |
| 1   | Desamortización de Godoy                         | Eclesiástica         | Paliar crisis comercio triangular y economía mercantilista                                                             |
| 2   | Desamortización de José (o del Estatuto de Bayona)| Eclesiástica         |                                                                                                                        |
| 3   | Desamortización de Cádiz                        | Eclesiástica         | Recaudar dinero para contrarrestar el déficit de hacienda y la deuda pública generada por la guerra de la Independencia |
| 4   | Desamortización del Trienio Liberal             | Eclesiástica         | Recaudar dinero para la hacienda y limitar el poder de la iglesia                                                               |
| 5   | Desamortización de Mendizábal                   | Eclesiástica         | Recaudar dinero para la hacienda, financiar la guerra y crear una clase de propietarios defensores del liberalismo            |
| 6   | Desamortización de Madoz                         | Eclesiástica y civil |                                                                                                                        |
| 7   | Desamortización del subsuelo                    | Subsuelo             |                                                                                                                        |

## Pronunciamientos 

### Respuesta

Un pronunciamiento es un acto de militares dirigidos por un alto cargo que tiene como objetivo provocar un cambio político, ya sea un cambio de gobierno o incluso instaurar una Constitución.

El siglo XIX en España estuvo marcado por la continua inestabilidad política, por lo que no es de extrañar que hubiera constantes pronunciamientos. A continuación procederemos a nombrar los más importantes; es decir, aquellos que tuvieron éxito y marcaron un cambio en el transcurso de la historia.

En primer lugar, el pronunciamiento de Riego en 1820, que tiene como objetivo reinstaurar la Constitución de 1812. Tras el pronunciamiento, se inicia el trienio liberal (1820-1823).

En segundo lugar, el pronunciamiento de Sargentos en la Granja, se produjo durante los gobiernos de transición durante la regencia de María Cristina (1833-1840). Se produjo porque María Cristina había instaurado un gobierno moderado lo cual disgustaba a los liberales. Tras esto, se forma un gobierno liberal con Calatrava como presidente y María Cristina acepta la Constitución de 1812.

En tercer lugar, el pronunciamiento de Narváez, Prim y O'Donnell en 1844, se produjo al final de la regencia de Espartero. Tuvo como objetivo adelantar la mayoría de edad de Isabel II y acabar con la regencia de Espartero (1840-1843) por las medidas represivas utilizadas en Barcelona. Tras el pronunciamiento se inicia la Década Moderada (1844-1854).

Por supuesto, aquí está el texto sin formato adicional:

---

En cuarto lugar, la Vicalvarada en 1854, pronunciamiento orquestado por O'Donnell e iniciado con el "Manifiesto de Manzanares", escrito por Cánovas del Castillo.

En quinto lugar, coincidiendo con la Gloriosa Revolución (1868), el pronunciamiento de Prim, Serrano y Topete, que tenía como objetivo acabar con la Monarquía de Isabel II. Se inicia con el Manifesto de España con honra.

En sexto lugar, el grito de Yara, alzamiento en Cuba, que tiene como objetivo pone inicio a la Guerra de los Diez años que acaba en 1878 con la paz de Zanjón.

En séptimo lugar, el pronunciamiento de Pavía en 1874, que tenía como objetivo acabar con el gobierno unitario de Emilio Castelar.

En octavo lugar, el pronunciamiento de Martínez Campos en Sagunto, tiene como objetivo suprimir la república, y establecer como monarca a Alfonso XII. Inicia la Restauración (1874-1931).

En noveno lugar, el grito de Baire (1895), el cual inicia la guerra Chiquita (1895-1898) en Cuba por el incumplimiento de la paz de Zanjón.

Finalmente, tenemos el golpe de Estado de Primo de Rivera en 1923.

### Tabla Resumen

| Nº | Pronunciamiento | Año | Objetivo |
|----|-----------------|-----|----------|
| 1  | Riego           | 1820| Reinstaurar Constitución de 1812 y Trienio Liberal |
| 2  | de Sargentos en la Granja | gobiernos transición Mª Cristina | Acabar con el gobierno moderado, instaurar uno liberal y que Mª Cristina acepte la Constitución de 1812 |
| 3  | de Narváez, Prim y O'Donnell | 1844 | Espartero, mayoría de edad de Isabel II |
| 4  | Vicalvarada     | 1854| Década Moderada → Bienio Progresista |
| 5  | (Gloriosa Revolución) Prim, Topete y Serrano | 1868| Isabel II |
| 6  | Grito de Yara   | 1868| Tratar de conseguir representación de Cuba en las Cortes Españolas |
| 7  | de Pavía        | 1874| Emilio Castelar |
| 8  | de Martínez Campos en Sagunto | 1874| República → Restauración |
| 9  | Grito de Baire   | 1895| Paz de Zanjón |
| 10 | Golpe de Estado de Primo de Rivera | 1923| Acabar con el sistema de la Restauración |

## Regencias
### Respuesta

Una regencia es un periodo en el que el papel del rey es ejecutado por un sustituto denominado regente, ya sea porque el rey esté incapacitado para reinar por ser todavía menor de edad o por enfermedad, o simplemente por su ausencia física. En España ha habido varias regencias, a continuación las vamos a exponer brevemente:

En primer lugar, durante la guerra de Independencia (1808-1812), ante la ausencia del monarca Fernando VII que estaba cautivo en Bayona, a partir de 1810 se inicia la regencia del obispo Orense, que sustituye a la junta suprema central. Durante su regencia, el obispo convocó las Cortes de Cádiz que promulgaron la Constitución de 1812. La regencia concluye en 1814 con la firma del tratado de Valençay que termina con la guerra y posibilita el regreso de Fernando VII.

En segundo lugar, la regencia de María Cristina de Borbón (1833-1840). La regencia se inicia tras la muerte de Fernando VII, ya que su hija Isabel II todavía era menor de edad y no podía heredar la corona. Este periodo está marcado por los constantes cambios de gobierno y por la liberalización de España, sobre todo por la reforma agraria y las medidas liberales de los gobiernos de Mendizábal y Calatrava. La regencia concluye en 1840 cuando los liberales progresistas liderados por el general Espartero se oponen a las medidas moderadas del gobierno, especialmente a la ley de ayuntamientos, que le confería a la corona el poder de elegir al alcalde de cada municipio.

En tercer lugar, la regencia de Espartero (1840-1843). Tras el fin de la regencia de María Cristina, como Isabel II seguía siendo menor de edad las Cortes eligen a Espartero como regente. Este periodo está marcado por las medidas liberales progresistas. Sin embargo, la regencia concluye abruptamente cuando Espartero bombardea Barcelona para hacer frente a las insurrecciones causadas por el arancel librecambista. Tras estos eventos, las Cortes deciden adelantar la mayoría de edad de Isabel II.

En cuarto lugar, la regencia de Serrano después de la Gloriosa Revolución de 1868. Tras el pronunciamiento de la Gloriosa Revolución de Topete, Serrano y Prim, se establece un gobierno provisional, el cual pone a Serrano como regente ante la ausencia de Monarca. Este periodo está caracterizado por las medidas democráticas recogidas en la Constitución de 1869, como la Monarquía Parlamentaria o el sufragio universal masculino. La regencia concluye cuando Amadeo I es nombrado monarca.

Por último, durante la Restauración tenemos la regencia de María Cristina de Habsburgo (1885-1902). En 1885 muere Alfonso XII y como Alfonso XIII todavía es menor de edad, entonces su madre María Cristina pasa a ser la regente. Esto supuso un duro golpe para el sistema Turnista. Tras esto, se firma el tratado del Pardo en el cual el partido Dinástico y el partido Liberal se comprometen a garantizar la supervivencia del sistema turnista.

### Tabla Resumen

| Regencia                                      | Fecha             |
|-----------------------------------------------|-------------------|
| Guerra de Independencia (Obispo Orense)        | 1810-1814         |
| María Cristina de Borbón                      | 1833-1840         |
| Baldomero Espartero                           | 1840-1843         |
| Serrano (Gloriosa Revolución)                 | 1868-1870         |
| María Cristina de Habsburgo                   | 1885-1902         |
