# Vocabulario (Pregunta 3)

## Definiciones

### El Reinado de Fernando VII

- **Antiguo Régimen:** Sistema social, económico y político utilizado en Europa antes del siglo XVIII. Se caracteriza por centralizar todos los poderes en la monarquía, que es elegida por la iglesia a través del derecho divino. La sociedad se encuentra dividida en estamentos, siendo el clero y la nobleza los estamentos privilegiados, mientras que económicamente predomina la economía de subsistencia basada en la agricultura y la ganadería.

- **Ilustración:** Movimiento económico, político, social y cultural nacido en Francia durante el siglo XVIII. Los pensadores ilustrados, como Jovellanos y Floridablanca, afirmaban que el conocimiento era una arma para luchar contra la ignorancia. De la Ilustración nacen conceptos como la libertad de pensamiento, los derechos humanos y la división de poderes.

- **Desamortización:** Estrategia económica que consiste en que el Estado expropie tierras sin uso o en "manos muertas" para recaudar dinero con su venta y aumentar la producción agrícola. Distinguimos dos tipos: eclesiásticas y civiles. A pesar de ser una estrategia económica, puede tener repercusión en la sociedad.

- **Manos muertas:** Tierras que no producen ni están en venta, por lo que no generan ningún tipo de beneficio. Tradicionalmente, la Iglesia ha poseído muchas "manos muertas", que al estar sin uso han sido desamortizadas justificadamente por el Estado.

- **Gremios:** Agrupaciones de artesanos que comparten el mismo oficio, aparecen durante el Feudalismo. Los gremios contaban con una estructura jerárquica que va desde el aprendiz al maestro, además de reglamentos internos que regulaban las actividades de sus miembros. Los gremios fueron una pieza clave para la economía de la época. Normalmente los integrantes del mismo gremio vivían en la misma zona.

- **Estatuto de Bayona:** Marco legislativo promovido por José I tras las abdicaciones de Fernando VII y Carlos IV, tiene como objetivo cambiar las leyes españolas para limitar el Antiguo Régimen. Algunas de sus medidas son: el fin de los privilegios y mayorazgos, la abolición de la Inquisición y la desamortización de la Iglesia.

- **Mayorazgo:** Institución del Antiguo Régimen que vinculaba las tierras y los títulos nobiliarios con los primogénitos que los heredaban. El contenido de la herencia debía pasar de generación en generación ya que no era posible venderlo. De esta forma, se lograba que la nobleza acumulara tierras y mantuviera el linaje.

- **Afrancesados:** Durante la invasión francesa de 1808 a 1814, minoría social conformada por numerosos ilustrados, altos funcionarios y alta nobleza que aceptaron a José I como rey tras la abdicación de Carlos IV y Fernando VII, porque deseaban distanciarse del Antiguo Régimen y acercarse más a las ideas ilustradas. Al acabar la Guerra de la Independencia, muchos se vieron obligados a exiliarse.

- **Patriotas:** Durante la invasión francesa de 1808 a 1814, mayoría social que se opuso a la invasión. La nobleza y el clero deseaban la vuelta del Antiguo Régimen de la mano de Fernando VII; mientras que algunos ilustrados esperaban compatibilizar su vuelta con la modernización del país. La burguesía y los intelectuales deseaban instaurar un sistema liberal-parlamentario y abolir los gremios. Mientras que los campesinos estaban en contra de los franceses porque los veían como invasores.

- **Parlamentarismo:** Sistema de gobierno basado en la separación de poderes, donde el gobierno (poder Ejecutivo) depende de un parlamento (poder Legislativo) conformado por representantes elegidos por el pueblo a través de las elecciones. El parlamento, además, aprueba leyes y toma decisiones políticas.

- **Guerra de guerrillas:** Estrategia militar en la cual pequeños grupos, conformados por civiles o paramilitares, asaltan al enemigo aprovechando el factor sorpresa, u otras artimañas como esconderse en zonas montañosas y esperar a que pase el enemigo. Esta estrategia es común en guerras de desgaste. El término fue acuñado en España durante la Guerra de la Independencia (1808-1814).

- **Tratado de Valençay:** Tratado firmado por Napoleón Bonaparte para terminar con la Guerra de la Independencia (1808-1814) y liberar a Fernando VII. Esto ocurre tras la guerra de guerrillas y el traslado de tropas para la guerra de Francia con Rusia.

- **Constitución:** Ley suprema o carta magna, es un documento que establece el marco legislativo de un país; de ella dependen el resto de leyes. Incluye también los derechos, deberes y libertades de los ciudadanos, los poderes del gobierno, la separación de poderes (Judicial, Legislativo y Ejecutivo), la estructura del gobierno (república o monarquía) y pautas de actuación frente a diferentes situaciones.

- **Regencia:** Persona o grupo de 3 o 5 personas que ejercen el papel de la figura del monarca cuando éste no se encuentra disponible para reinar por una de las siguientes razones: es menor de edad, está físicamente ausente o está enfermo y no es capaz de ejercer. Normalmente, cuando el heredero al trono era menor de edad, su madre solía ser la regente.

- **Laicismo:** Corriente ideológica que promueve la independencia del Estado con cualquier religión. Es lo contrario de confesionalidad, la cual fomenta una religión oficial. El movimiento se origina en Francia durante la Revolución Francesa. Además, España ha sido un estado laico tres veces: en las dos repúblicas y tras la Constitución de 1978.

- **Sufragio:** Derecho recogido en la Constitución del grupo de la población que a nivel legislativo se encuentra en capacidad de votar. Distinguimos diferentes tipos de sufragio tales como el sufragio universal o el sufragio masculino. Algunos criterios para elegir quién puede votar son el género, la edad, la etnia o la formación.

- **Milicia Nacional:** Grupo organizado de civiles armados cuya función era defender el liberalismo y la Constitución. La primera fue establecida por la Constitución de 1812, promulgada durante la Guerra de la Independencia (1808-1814). Fue disuelta por Fernando VII con el restablecimiento del Antiguo Régimen.

- **Cortes:** Grupo de personas conformado por diputados y senadores que han de representar a toda la población de un estado. Las cortes ejercen el poder Legislativo y han de controlar la acción del gobierno (poder Ejecutivo), además de redactar las leyes. En España están conformadas por el Congreso de los Diputados y el Senado.

- **Manifiesto de los Persas:** Documento publicado tras la vuelta de Fernando VII a España. Tiene como objetivo incitar al monarca a reinstaurar el Antiguo Régimen y abolir la Constitución de 1812 promulgada por las Cortes de Cádiz. La escritura del manifiesto fue impulsada por la Iglesia y la nobleza, que pretendían recuperar sus privilegios.

- **Pronunciamiento:** Acto de militares dirigidos por un alto cargo que tiene como objetivo provocar un cambio político, ya sea un cambio de gobierno o incluso instaurar una constitución. Durante el siglo XIX en España hubo muchos pronunciamientos, sin embargo, la gran inmensa mayoría fracasaron. Mientras que unos pocos, como el de Riego en 1820, tuvieron éxito.

- **Liberalismo:** Ideología política y económica que promueve la libertad individual, el Estado de derecho y el laicismo como pilares fundamentales para la creación de una sociedad. La economía del régimen liberal es librecambista y está basada en la ley de la oferta y la demanda. Mientras que en el ámbito social promueve la igualdad de oportunidades entre los ciudadanos aunque aparecen las clases sociales. Los ilustrados promueven el liberalismo en contra del Antiguo Régimen. Fue expandido por Europa gracias a la Revolución Francesa.

- **Separación de poderes:** Principio que implica dividir las funciones del Estado en tres poderes independientes. El poder Ejecutivo implementa las leyes y políticas, el poder Legislativo redacta y aprueba leyes y está representado por las Cortes. Mientras que el poder Judicial interpreta y aplica las leyes a través de los jueces. La separación de poderes fue propuesta por Montesquieu y está recogida en la Constitución.

- **Amnistía:** Concepto legal que hace referencia al perdón de las sanciones a quienes han cometido algún delito. Por ejemplo, al inicio del Trienio Liberal tras el pronunciamiento de Riego se proclama una amnistía por la cual los liberales y los afrancesados pueden volver a España.

- **Derecho de Veto:** Capacidad del monarca recogida en la Constitución para rechazar leyes y propuestas de las Cortes (poder Legislativo). Durante el Trienio Liberal (1820-1823), Fernando VII lo emplea para frenar leyes de las Cortes y así retrasar el avance del liberalismo en España.

- **Realistas:** Grupos que apoyan a la monarquía como sistema de gobierno, además del Antiguo Régimen. Están en contra del liberalismo y de los sistemas de gobierno como la república. Estaban conformados por miembros de la nobleza y la Iglesia.

- **Cien Mil Hijos de San Luis:** Ejército francés enviado por la Santa Alianza que tenía como objetivo poner fin al régimen constitucional establecido en España tras el pronunciamiento de Riego (1820) y establecer a Fernando VII como monarca absolutista. Entraron en España en 1823, dirigidos por el duque de Angulema.

- **Ley Sálica:** Ley que elimina el derecho al trono de las mujeres. En España, fue primero implantada por Felipe V. Fernando VII, influenciado por su esposa, promulgó la Pragmática Sanción para garantizar que su hija Isabel II accediera al trono.

- **Pragmática Sanción:** Ley promulgada por Fernando VII por influencia de su esposa María Cristina, para abolir la Ley Sálica, la cual impedía a su hija Isabel II reinar. Esto causó que algunas personas no reconocieran a Isabel II como reina, sino que apoyaran a Carlos María Isidro (hermano de Fernando VII), lo que desencadenó el Carlismo.

- **Burguesía criolla:** Descendientes de españoles nacidos en América. Su riqueza se generaba por la venta de productos como café o patatas, gracias al comercio colonial y mercantilista. Jugaron un papel importante en la independencia de las colonias españolas por su dominio de las ideas ilustradas.

- **Soberanía Nacional:** Concepto ilustrado definido por Rousseau, que dicta que el poder de la nación recae sobre los ciudadanos, quienes a través del voto delegan su poder en los representantes de las Cortes.

- **Soberanía:** Autoridad máxima dentro de un Estado; es decir, sobre quien recae el poder del estado. Distinguimos distintos tipos como: la Nacional, la Compartida o la Popular. Se encuentra especificada en la Constitución vigente.

- **Mesta:** Privilegio que gozaban los ganaderos por el cual podían transitar libremente por las cañadas reales, además también estaban exentos de algunos impuestos. Durante el reinado de Fernando VII (1808-1833) fue abolido y reimplantado varias veces hasta su supresión definitiva por los gobiernos de María Cristina.

***
### La liberalización, la regencia de Mª Cristina, el reinado de Isabel II y el Sexenio Democrático

- **Carlismo:** movimiento político español que promueve a Carlos María Isidro y su descendencia como monarcas de España. Estaban enfrentados contra los cristinos o isabelinos porque Fernando VII había promulgado la Pragmática Sanción para abolir la Ley Sálica y permitir que Isabel II reinara. Mantenían una ideología conservadora y su lema era: "Dios, Patria, Rey/Fueros".

- **Isabelinos:** también conocidos como cristinos, eran el movimiento político que promovía a Isabel II como heredera al trono. Estaban enfrentados con los carlistas porque Fernando VII promulgó la Pragmática Sanción para abolir la Ley Sálica, la cual inhabilitaba a Isabel II como candidata al trono. Mantenían una ideología liberal moderada.

- **Fueros:** leyes que otorgaban privilegios a una zona, ciudad o persona, generalmente otorgados por el monarca. En el siglo XIX, el gobierno liberal de María Cristina eliminó los fueros, y durante la Primera Guerra Carlista (1833-1840), además de pelear por el trono de España, los carlistas lucharon por la reinstauración de los fueros.

- **Quintas:** sistema de reclutamiento militar que consistía en realizar un sorteo entre los jóvenes varones mayores de edad. Fue utilizado en España durante la Primera Guerra Carlista (1833-1840). Las familias burguesas o la nobleza, a veces, evitaban el reclutamiento mediante sobornos o pagando a alguien más pobre para que acudiera al servicio.

- **Transaccionistas e intransigentes:** durante la Primera Guerra Carlista (1833-1840), el carlismo se dividió en dos vertientes. Los transaccionistas proponían un acuerdo con los liberales para detener la guerra civil, mientras que los intransigentes deseaban continuar con la guerra. Finalmente, la guerra terminó con el Convenio de Vergara (1839).

- **Diezmo:** impuesto que se pagaba durante la Edad Media y la Edad Moderna, consistía en entregar el 10% (de ahí el nombre) de los beneficios agrícolas a la iglesia local que los utilizaba para financiar actividades religiosas. Este impuesto solo lo pagaban los campesinos, para quienes era una gran carga. Durante el siglo XIX, se eliminó y se reimplantó varias veces hasta su abolición definitiva.

- **Monarquía parlamentaria o constitucional:** sistema político donde el monarca es el jefe del estado, pero está sometido a la Constitución vigente y al parlamento (poder legislativo). El monarca toma un papel ceremonial y representativo, mientras que el poder de tomar decisiones políticas recae sobre el presidente y el gobierno (poder ejecutivo).

- **Señoríos:** también llamados feudos, eran territorios controlados por un señor feudal que pertenecía a la nobleza. Los señores feudales tenían como súbditos a los campesinos, quienes trabajaban la tierra a cambio de protección. Durante el siglo XIX, progresivamente, los feudos de los señores feudales pasaron a ser tierras de un dueño, quien si deseaba que las tierras se trabajaran, debía alquilarlas o contratar trabajadores.

- **Moderantismo:** corriente política que apareció en España durante la regencia de María Cristina, con el objetivo de compatibilizar los poderes de la monarquía con las ideas liberales e ilustradas y la confesionalidad del estado mediante una monarquía constitucional. Sus características incluían restringir las libertades y el sufragio censatario, y rehuir tanto las ideas absolutistas como las liberales extremas, buscando el equilibrio.

- **Camarilla de Isabel II:** grupo de personas leales y cercanas a la reina Isabel II que, durante su reinado (1833-1868), influyeron en gran medida en sus decisiones. Algunos de sus miembros eran María Cristina y Francisco de Asís (su marido).

- **Oligarquía:** sistema de gobierno en el cual el poder de la nación recae sobre un grupo de personas pertenecientes a una clase social privilegiada. En la Década Moderada (1844-1854), parte del poder recaía sobre un grupo de personas ricas e influyentes como la burguesía o la nobleza, ya que el sufragio era censatario.

- **Sufragio censatario:** sistema de votación en el cual únicamente pueden votar aquellos que cumplan determinadas condiciones económicas, sociales o de formación. Durante la Década Moderada (1845-1854), el sufragio era censatario e inferior al 1%, lo cual causaba que solo pudieran votar la iglesia, el ejército y grandes contribuyentes.

- **Culto y clero:** acuerdo por el cual el Estado se comprometía a financiar a la Iglesia Católica, mientras que la Iglesia se comprometía con la educación y los hospitales. Este acuerdo se reforzó tras el Concordato de la Santa Sede, firmado en la Década Moderada (1845-1854).

- **Impuesto de consumos:** tasa impuesta en la Década Moderada (1845-1854) tras la reforma fiscal de Món-Santillán, por la que la gente que compraba ciertos productos de consumo diario pagaba una cantidad adicional que servía para llenar las arcas del Estado.

- **Vicalvarada:** pronunciamiento de 1854 iniciado tras la publicación del Manifiesto de Manzanares escrito por Cánovas del Castillo y formado por O'Donnell. Tenía como objetivo restablecer la Milicia Nacional, reducir los impuestos y reformar la ley electoral, además de acabar con la camarilla de Isabel II. Puso fin a la Década Moderada (1845-1854) e inició el Bienio Progresista (1854-1856).

- **Huelga general:** paro organizado por los trabajadores de todos los sectores para presionar al gobierno a realizar cambios en condiciones laborales o salarios. Suelen ser convocadas por las asociaciones de trabajadores.

- **Moción de censura:** procedimiento parlamentario recogido en la Constitución en el cual un grupo de diputados muestra su desacuerdo con el gobierno vigente para forzar su destitución. Si la moción de censura es aprobada, el gobierno debe renunciar y se elige uno nuevo. El gobierno de O'Donnell sufrió un intento de moción de censura al final del Bienio Progresista (1854-1856).

- **Unionista:** movimiento del partido político "Unión Liberal" fundado por O'Donnell. Era un partido de centro que concentraba a los más conservadores de entre los progresistas y a los liberales más moderados. Tras el Bienio Progresista (1854-1856) estuvo al frente del gobierno.

- **Democracia:** sistema político en el cual los ciudadanos ejercen la soberanía nacional mediante elecciones. Se caracteriza por el respeto de los derechos humanos, el estado de derecho, la separación de poderes, la igualdad ante la ley, y la representación de distintas ideologías por diferentes partidos políticos. A partir de mediados del siglo XIX se empieza a expandir por Europa.

- **Diputación:** institución administrativa destinada a representar los intereses de las provincias españolas. En el siglo XIX, gestionaban la recaudación de impuestos y las obras públicas, además de intermediar entre los municipios y el gobierno central. En el Sexenio Democrático (1868-1874) aparecieron las elecciones a diputación, que contribuyeron a la descentralización del Estado.

- **Hambre de Algodón:** crisis económica que afectó a España, iniciada cuando durante la Guerra de Secesión Americana se detuvo la producción de algodón que se importaba a Europa, causando un aumento en su precio. Esta crisis tuvo gran repercusión en España ya que su industria estaba poco desarrollada y, además, se enfrentaba a una crisis financiera y de subsistencia.

- **República:** forma de gobierno donde el poder reside en el pueblo y en sus representantes elegidos, en lugar de en un monarca hereditario. En una república, el jefe de Estado y otros funcionarios son elegidos por el pueblo, y el país es gobernado por leyes recogidas en la Constitución. Además, se rige por la soberanía popular. A partir de la Revolución Francesa se extiende por Europa.

- **Cantonalismo:** movimiento republicano federalista que apareció en España durante la Primera República (1873-1874). Fomentado por los federalistas intransigentes, basaban el cantonalismo en las ideas anárquicas de la AIT. Consistía en que varias regiones declararan su independencia y formaran su propio gobierno autónomo, con el objetivo de descentralizar el poder. El ejemplo más característico es el cantón de Cartagena.
***

### La transformación industrial y agraria del siglo XIX

- **Ciclo Demográfico Antiguo:** demografía característica del Antiguo Régimen, marcada por una alta mortalidad debido a la abundancia de epidemias y la falta de higiene, especialmente en zonas rurales donde la medicina no estaba suficientemente avanzada. También presentaba una alta natalidad, ya que la economía mayoritariamente agraria utilizaba a los hijos como mano de obra. En España, este ciclo estuvo presente desde el feudalismo hasta el primer tercio del siglo XIX.
- **Transición demográfica:** proceso de cambio demográfico impulsado por la mejora de las condiciones sanitarias y la higiene, resultado del desarrollo de la industria que posibilitó un descenso de la mortalidad. En España, la transición más significativa se produjo en el primer tercio del siglo XIX, dejando atrás el Ciclo Demográfico Antiguo y pasando a una demografía más moderna.
- **Indianos:** españoles que emigraban a América con el objetivo de enriquecerse y, al lograrlo, regresaban a España para realizar acciones filantrópicas. Este fenómeno, conocido popularmente como "hacer las Américas", involucró principalmente a emigrantes de Asturias, Galicia y Cantabria, quienes se dirigían a países como Argentina y México.
- **Latifundio:** propiedades agrícolas de grandes dimensiones utilizadas para la agricultura. En España, durante el siglo XIX, estos terrenos se encontraban predominantemente en Extremadura, Castilla-La Mancha y Andalucía, debido a la orografía. A pesar de su existencia, apenas hubo avance agrario en estos latifundios durante el siglo XIX.
- **Minifundio:** propiedades agrarias de pequeñas dimensiones utilizadas para la agricultura. En España, durante el siglo XIX, predominaban en la vertiente mediterránea y el norte, debido a la mala orografía del país. Los señores contrataban jornaleros para trabajar las tierras o las alquilaban.
- **Indianas:** telas con estampado de colores que tuvieron gran éxito en Europa, provenientes de la India. Antes de la industrialización española, Cataluña atrajo inversores con la producción de estas telas peculiares.
- **Colonia industrial:** asentamientos de civiles cerca de un río para aprovechar la energía producida por un salto de agua. Estos asentamientos estaban constituidos por distintos edificios, como la mansión del propietario, las fábricas y viviendas para los trabajadores y sus familias. Aparecieron en España tras la industrialización de Cataluña.
- **Altos hornos:** instalaciones industriales destinadas a la producción de hierro, utilizado principalmente en la fabricación de acero. Requerían grandes cantidades de carbón para alcanzar altas temperaturas. En España, los primeros altos hornos aparecieron en Andalucía.

***

### La transformación social del siglo XIX

- **Estamentos:** sistema de organización característico del feudalismo, la población se dividía en tres grupos: nobleza, clero y campesinado. Estos grupos o estamentos eran fijos, no se podía cambiar de uno a otro, y el estamento de cada persona era determinado en el momento de nacimiento. Con la abolición del Antiguo Régimen, los estamentos fueron reemplazados por las clases sociales.
- **Hidalgos:** miembros de la baja nobleza que vivían gracias a la recaudación de impuestos. Con la abolición del Antiguo Régimen y la eliminación de todos los privilegios, pasaron a integrarse en la clase media.
- **Socialismo:** ideología política, económica y social que busca que el Estado controle la producción de bienes y servicios. Distinguimos dos corrientes: el Socialismo Utópico propuesto por Robert Owen y el Socialismo Científico o Marxismo de Karl Marx. Es una ideología presente dentro de la AIT.
- **Anarquismo:** ideología iniciada por el filósofo Bakunin que propone la abolición del Estado y cualquier forma de gobierno o jerarquía, además de la cooperación voluntaria y la autogestión. Distinguimos distintas vertientes como el anarcocomunismo y el anarcosindicalismo. Es una ideología recogida en la AIT.
- **Anarcocomunismo:** vertiente del anarquismo que aboga por la supresión del Estado y cualquier forma de gobierno, así como de la propiedad privada. Es una mezcla entre el anarquismo y el comunismo, y opta por el uso de la acción directa y los magnicidios. El cantonalismo que aparece durante la Primera República (1873-1874) pertenece al anarcocomunismo.
- **Anarcosindicalismo:** corriente de pensamiento anarquista que mediante el uso de sindicatos (asociaciones de trabajadores como la CNT) propone la emancipación de la clase trabajadora y la creación de una sociedad sin clases sociales, además de abolir el concepto del Estado.
- **Ludismo:** movimiento social originado en Inglaterra durante la Revolución Industrial. Los luditas eran miembros del proletariado que luchaban contra las máquinas porque amenazaban sus puestos de trabajo. Para lograr su objetivo mandaban cartas amenazantes a la patronal o cometían actos mecanoclastas.
- **Sociedades de protección mutua:** organizaciones voluntarias conformadas por miembros del proletariado que pagaban una cuota mensual. Tenían como objetivo proporcionar dinero a los afiliados que no podían trabajar, ya fuera por un despido o por estar enfermos.

### La Restauración: el regreso de la monarquía y el fin del imperio

- **Caciques/Caciquismo:** individuos o familias que, por poder económico o influencias políticas, controlaban el sistema electoral por orden del gobierno, motivando a los electores a votar a determinado partido político o amañando directamente las elecciones mediante el "pucherazo". Aparecen en España durante la Restauración (1874-1931).
- **Pucherazo:** fraude electoral o manipulación que se realiza con el objetivo de que determinado partido gane las elecciones. Para ello hay distintas artimañas: comprar votos, eliminar urnas, votar por gente muerta... Durante la Restauración (1874-1931), los caciques lo utilizaban.
- **Encasillamiento:** documento redactado por el Ministerio de Gobernación durante la Restauración (1874-1931). Contenía la asignación de los diputados que tenían que resultar elegidos en las próximas elecciones para garantizar la continuación del sistema turnista o canovista. El documento era remitido a los caciques y a los alcaldes.
- **Turnismo:** sistema de gobierno utilizado en la Restauración (1874-1931), diseñado por Cánovas del Castillo, basándose en el de Gran Bretaña, con el objetivo de alcanzar la estabilidad política. Se basa en cuatro pilares: el rey como cabeza simbólica del ejército (para evitar pronunciamientos), los partidos dinásticos (el liberal y el conservador, que protegían el sistema), el rey como árbitro político (decide cuándo gobierna cada partido) y la Constitución de 1876.
- **Arancel Cánovas:** impuesto o carga fiscal sobre los productos que importaba Cuba que no fueran de España. Era una medida proteccionista ya que eliminaba a toda la competencia. Esto molestaba mucho a Estados Unidos, que no podía vender sus productos. Por esto, durante la guerra Chiquita (1895-1898) intervino a favor de Cuba.

***

### La crisis de la Restauración, la Dictadura de Primo de Rivera

- **Protectorado:** forma de gobierno de una colonia en la cual mantenían autonomía propia en el ámbito interior. Sin embargo, la política exterior era gestionada por el país colonizador. España, después del tratado de 1912 y la Conferencia de Algeciras (1906), consiguió un protectorado en Marruecos que tuvo que gestionar conjuntamente con Francia.
- **Regeneracionismo:** corriente ideológica impulsada por Joaquín Costa y otros autores que intentaban frenar el deterioro de España después del desastre del 98 (la pérdida de las colonias). Se ubica a finales del siglo XIX y a principios del siglo XX. La sustitución de Cánovas y Sagasta por Maura y Canalejas contribuyó a la regeneración del sistema político, ya que trataban de reducir el caciquismo.
- **Cabilas:** tribus bereberes situadas en el norte de África. A principios del siglo XX, España tuvo un protectorado en Marruecos donde las cabilas atacaban a las tropas españolas. El incidente más destacable fue la masacre del Barranco del Lobo.
- **Estado de guerra:** situación excepcional recogida en la Constitución en la que un país entra en un conflicto bélico. En esta situación, el Estado toma medidas especiales como restringir los derechos (por ejemplo, el de reunión) y las libertades, o la ampliación de los poderes y funciones del poder Ejecutivo y de los militares, quienes pueden realizar juicios militares. España, durante la Semana Trágica (1909), entró en este estado.
- **CNT:** Confederación Nacional de Trabajadores, sindicato de carácter anarcosindicalista, que trata de abolir el Estado y sus leyes. Aparece en España durante el primer tercio del siglo XX. Por ejemplo, durante la Gran Guerra realizó un congreso por la paz en El Ferrol.
- **Pistolerismo:** pistoleros contratados por la patronal para luchar contra el sindicalismo. Asesinaban a los dirigentes obreros y a los sindicatos. Aparecen en España durante la Restauración (1874-1931). Tras la crisis del 17, aparece la Federación Patronal que contratará a estos pistoleros. La situación empeorará drásticamente con la ley de fugas.
- **Ley Marcial:** ley recogida en la Constitución, la cual, en situaciones excepcionales como huelgas generales, dota a los militares de una ampliación de sus poderes y funciones. Durante la Restauración (1874-1931), en la crisis de 1917, se aplicó la Ley Marcial.
- **Golpe de Estado:** acto realizado por los militares dirigidos por uno de mayor rango que mediante la fuerza consiguen realizar un cambio a nivel político aboliendo el gobierno actual e iniciando una dictadura. Durante el siglo XX destaca el Golpe de Estado de Miguel Primo de Rivera para evitar la difusión de los resultados del expediente Picasso.
- **Gobiernos de Concentración:** sistema de gobierno donde el gobierno integra diferentes miembros de diferentes partidos para afrontar una situación de crisis. Por ejemplo, después del desastre de Annual, para hacer frente a las constantes insurrecciones, se recurrió a este sistema de gobierno.
- **Corporativismo:** forma de organización social y económica en la que los diferentes grupos de la sociedad están estructurados en corporaciones. Su objetivo es lograr la armonía entre las clases sociales. Es una característica propia de la dictadura militar de Primo de Rivera, aunque también es una característica del fascismo.
- **Plebiscito:** votación en la cual el electorado tiene que aceptar o rechazar una propuesta. Las elecciones de 1931, a pesar de no ser un plebiscito como tal, acabaron siéndolo ya que la gente votaba en contra o a favor de la monarquía. Tras esto se pone fin a la Restauración (1874-1931) y se inicia la Segunda República.
- **Dictadura:** sistema de gobierno impuesto tras un golpe de Estado donde todos los poderes del Estado recaen sobre el dictador. Durante las dictaduras, la Constitución se suprime, así como otros derechos y libertades de los ciudadanos. También se caracterizan por medidas autoritarias o autárquicas. España ha sufrido dos dictaduras: la de Primo de Rivera (1923-1930) y la de Francisco Franco.
    - La de Primo de Rivera se caracteriza por el corporativismo y se basa en el fascismo.
    - La de Franco se caracteriza por la creación del "Movimiento" y se basa en el nazismo.

### Otras
- **Bienes comunales:** conjunto de tierras que pertenecen a un ayuntamiento las cuales son de uso común; es decir, para todos los habitantes de un municipio, por ejemplo, las montañas boscosas sin explotar. En la desamortización de Madoz del Bienio Progresista (1854-1856), estas tierras también son expropiadas.
- **Censo:** recuento de la población clasificada por su lugar de residencia. El censo tiene distintas utilidades, por ejemplo: tomar decisiones políticas en función del número de habitantes de una zona, gestionar la recaudación de impuestos, generar los distritos electorales en las elecciones, etc.
- **Censura:** {orientada al s.XIX} acto de suprimir deliberadamente la difusión de información o ideas. Este control es ejercido por varios organismos. En España, durante el siglo XIX, era ejercida por la Monarquía y por la Iglesia a través de la Inquisición para evitar la difusión de las ideas ilustradas, republicanas o liberales y/o anticlericales.
- **Confesionalidad:** carácter religioso de una religión como oficial y se compromete a respaldarla. En España, la religión oficial siempre ha sido el catolicismo. La iglesia cobraba el diezmo, pero asumía ciertas competencias del ámbito educativo y sanitario. Además, también ejercía la censura a través de la Inquisición.
- **Directorio Militar:** periodo de la dictadura militar de Miguel Primo de Rivera comprendido entre 1923 y 1925. Se caracteriza por el orden público generado por medidas autoritarias y represivas como: la supresión de Cortes y Constitución, ilegalización de sindicatos y partidos políticos, y la supresión de los ayuntamientos.
- **Libertad de imprenta:** libertad de imprimir y distribuir información sin censura por parte del gobierno o la Inquisición. En España, aparece por primera vez en la Constitución de 1812 redactada en las Cortes de Cádiz.
- **Gobierno Constitucional:** gobierno el cual está controlado por la Constitución, la máxima ley que establece qué pueden hacer tanto el gobierno como los ciudadanos. Es una característica de la Restauración (1874-1931).
- **Reaccionario:** {relativo al carlismo} grupos de personas que, frente a una ley o propuesta, mantienen una actitud de rechazo para evitar su ejecución. En España, durante la 1ª Guerra Carlista (1833-1840), los reaccionarios buscaban la restauración de los fueros y que el trono fuera heredado por Carlos María Isidro. También se les conoce como Carlistas.
- **Reforma agraria:** conjunto de medidas implementadas por el gobierno que tiene como objetivo redistribuir las tierras y los recursos agrícolas. Durante la primera mitad del siglo XIX español, hubo bastantes reformas agrarias. Destacan las de los gobiernos liberales de Mendizábal y Calatrava durante la Regencia de María Cristina (1833-1840).
- **Soberanía Compartida:** característica de un Estado recogida en la Constitución en la cual su máxima autoridad o soberanía recae sobre dos o más organismos. Durante la Restauración (1874-1931), la soberanía era compartida entre el monarca (que tenía el papel de árbitro político) y las Cortes.
- **Sufragio Universal Masculino:** sistema de votación recogido en la Constitución en el cual pueden votar todos los hombres sin importar sus condiciones económicas o sociales, siempre que superen la mayoría de edad. Se trata de una medida progresista. En el siglo XIX español, aparece por primera vez en el Sexenio Democrático (1868-1874) y en la Restauración (1874-1931) aparece en 1890.

## Estudio estadístico

Se ha realizado un conteo de palabras para determinar aquellas que han salido con más frecuencia. El estudio incluye desde la convocatoria de junio del 2010 hasta la de julio del 2024.

| Palabra                      | Frecuencia |
| ---------------------------- | ---------- |
| Absolutismo                  | 6          |
| Golpe de Estado              | 4          |
| Liberalismo                  | 4          |
| Constitución                 | 3          |
| Dictadura                    | 3          |
| División de Poderes          | 3          |
| Soberanía                    | 3          |
| Soberanía Nacional           | 3          |
| Amnistía                     | 2          |
| Caciquismo                   | 2          |
| Carlistas                    | 2          |
| Censura                      | 2          |
| Huelga General               | 2          |
| Isabelinos                   | 2          |
| Ley Sálica                   | 2          |
| Pronunciamiento              | 2          |
| Sufragio Censatario          | 2          |
| Abdicación                   | 1          |
| Afrancesados                 | 1          |
| Anarquismo                   | 1          |
| Bicameralismo                | 1          |
| Bienes Comunales             | 1          |
| Cambio de Régimen            | 1          |
| Censo                        | 1          |
| Cien Mil Hijos de San Luis   | 1          |
| Ciudadano                    | 1          |
| Confesionalidad              | 1          |
| Democracia                   | 1          |
| Desamortización              | 1          |
| Directorio Militar           | 1          |
| Gobierno Constitucional      | 1          |
| Guerrillas                   | 1          |
| Inquisición                  | 1          |
| Laicismo                     | 1          |
| Legitimismo                  | 1          |
| Libertad de Imprenta         | 1          |
| Librecambismo                | 1          |
| Moderados                    | 1          |
| Monarquía                    | 1          |
| Monarquía Parlamentaria      | 1          |
| Progresistas                 | 1          |
| Proteccionismo               | 1          |
| Reaccionario                 | 1          |
| Reforma Agraria              | 1          |
| República Federal            | 1          |
| Señorío                      | 1          |
| Soberanía Compartida         | 1          |
| Socialismo                   | 1          |
| Sociedad Patriótica          | 1          |
| Sufragio Universal Masculino | 1          |
| Transición Demográfica       | 1          |
| Turnismo                     | 1          |

## Palabras *Top 25*

Con el objetivo de preparar la PAU, a continuación se encuentran recopiladas por orden alfabético las palabras que considero que es altamente probable que pregunten o que vuelvan a salir.

- **Absolutismo:** sistema social, económico y político utilizado en Europa antes del siglo XVIII. Se caracteriza por centralizar todos los poderes en la monarquía que es elegida por la iglesia a través del derecho divino. La sociedad se encuentra dividida en estamentos, siendo el clero y la nobleza los estamentos privilegiados. Mientras que económicamente predomina la economía de subsistencia basada en la agricultura y la ganadería.

- **Amnistía:** concepto legal que hace referencia al perdón de las sanciones a quienes han cometido algún delito. Por ejemplo, al inicio del Trienio Liberal tras el pronunciamiento de Riego se proclama una amnistía por la cual los liberales y los afrancesados pueden volver a España.

- **Anarquismo:** ideología iniciada por el filósofo Bakunin que propone la abolición del estado y cualquier forma de gobierno o jerarquía. Además de proponer la cooperación voluntaria y la autogestión. Distinguimos distintas vertientes como el anarcocomunismo y el anarcosindicalismo. Se trata de una ideología recogida en la AIT.

- **Caciques/Caciquismo:** individuos o familias que por poder económico o influencias políticas controlaban por orden del gobierno el sistema electoral, ya sea motivando a los electores a votar a determinado partido político o amañando directamente las elecciones mediante "el pucherazo". Aparecen en España durante la Restauración (1874-1931).

- **Carlismo:** movimiento político español que promueve a Carlos María Isidro y su descendencia como monarcas de España. Estaban enfrentados contra los cristinos o isabelinos porque Fernando VII había promulgado la Pragmática Sanción para abolir la ley Sálica y permitir que Isabel II reine. Mantienen una ideología conservadora y su lema es: "Dios, Patria, Rey/Fueros".

- **Censura:** {orientada al s.XIX} acto de suprimir deliberadamente la difusión de información o ideas. Este control es ejercido por varios organismos; en España durante el siglo XIX era ejercida por la Monarquía y por la Iglesia a través de la Inquisición para evitar la difusión de las ideas ilustradas, republicanas, liberales y/o anticlericales.

- **Constitución:** Ley suprema o carta magna, es un documento que establece el marco legislativo de un país, de ella dependen el resto de leyes. Incluye también los derechos, deberes y libertades de los ciudadanos, los poderes del gobierno, la separación de poderes (Judicial, Legislativo y Ejecutivo), la estructura del gobierno (república o monarquía) o pautas de actuación frente a diferentes situaciones.

- **Democracia:** sistema político en el cual los ciudadanos ejercen la soberanía nacional mediante las elecciones. Se caracteriza por el respeto de los derechos humanos, el estado de derecho, la separación de poderes, la igualdad ante la ley y la representación de las distintas ideologías por los diferentes partidos políticos. A partir de mediados del siglo XIX se empieza a expandir por Europa.

- **Dictadura:** sistema de gobierno impuesto tras un golpe de estado donde todos los poderes del estado recaen sobre el dictador. Durante las dictaduras, la constitución se suprime, así como otros derechos y libertades de los ciudadanos. También se caracterizan por medidas autoritarias o autárquicas. España ha sufrido dos dictaduras: la de Primo de Rivera (1923-1930) y la de Francisco Franco.
  - La de Primo de Rivera se caracteriza por el corporativismo y se basa en el fascismo.
  - La de Franco se caracteriza por la creación del "Movimiento" y se basa en el nazismo.

- **División de Poderes:** principio que implica dividir las funciones del estado en tres poderes independientes. El poder Ejecutivo implementa las leyes y políticas, el poder Legislativo redacta y aprueba leyes, está representado por las cortes. Mientras que el poder Judicial interpreta y aplica las leyes a través de los jueces. La separación de poderes fue propuesta por Montesquieu y está recogida en la constitución.

- **Golpe de Estado:** acto realizado por los militares dirigidos por uno de mayor rango que mediante la fuerza consiguen realizar un cambio a nivel político, aboliendo el gobierno actual e iniciando una dictadura. Durante el siglo XX destaca el Golpe de Estado de Miguel Primo de Rivera para evitar la difusión de los resultados del expediente Picasso.

- **Huelga general:** paro organizado por los trabajadores de todos los sectores. De esta forma todos los trabajadores presionan al gobierno para realizar algún cambio, ya sea de condiciones laborales o salario. Suelen ser convocadas por las asociaciones de los trabajadores.

- **Isabelinos:** también conocidos como cristinos, movimiento político que promovía a Isabel II como heredera al trono. Estaban enfrentados con los carlistas porque Fernando VII promulgó la Pragmática Sanción para abolir la ley Sálica, la cual inhabilitaba a Isabel II como candidata al trono. Mantiene una ideología moderada liberal.

- **Ley Sálica:** ley que elimina el derecho al trono de las mujeres. En España el primero en implantarla fue Felipe V. Fernando VII, influido por su esposa, promulga la Pragmática Sanción para garantizar que su hija Isabel II acceda al trono.

- **Liberalismo:** ideología política y económica que promueve la libertad individual, el estado de derecho y el laicismo como pilares fundamentales para la creación de una sociedad. La economía del régimen liberal es librecambista y está basada en la ley de la oferta y la demanda. Mientras que en el ámbito social promueve la igualdad de oportunidades entre los ciudadanos aunque aparecen las clases sociales. Los ilustrados promueven el liberalismo en contra del Antiguo Régimen. Fue expandido por Europa gracias a la Revolución Francesa.

- **Monarquía parlamentaria o constitucional:** sistema político donde el monarca es el jefe del estado, el cual está sometido a la Constitución vigente y al parlamento (poder Legislativo). El monarca pasa a tomar un papel ceremonial, representativo o testimonial, ya que el poder de tomar decisiones políticas recae sobre el presidente y el gobierno (poder Ejecutivo).

- **Pragmática Sanción:** ley promulgada por Fernando VII por influencia de su esposa Mª Cristina, para abolir la ley Sálica, la cual impedía a su hija Isabel II reinar. Esta causa que haya gente que no reconozca a Isabel II como reina, sino a Carlos Mª Isidro (hermano de Fernando VII) como monarca, lo que desencadena el Carlismo.

- **Pronunciamiento:** acto de militares dirigidos por un alto cargo que tiene como objetivo provocar un cambio político, ya sea un cambio de gobierno o incluso instaurar una constitución. Durante el siglo XIX en España hubo muchos pronunciamientos, sin embargo, la gran mayoría fracasaron. Mientras que unos pocos, como el de Riego en 1820, tuvieron éxito.

- **República:** forma de gobierno donde el poder reside en el pueblo y en sus representantes elegidos, en lugar de estar en un monarca hereditario. En una república, el jefe de Estado y otros funcionarios son elegidos por su pueblo, el país es gobernado por leyes recogidas en la constitución. Además, se rigen por la soberanía popular. A partir de la Revolución Francesa se extiende por Europa.

- **Soberanía:** autoridad máxima dentro de un Estado; es decir, sobre quien recae el poder del estado. Distinguimos distintos tipos como: la Nacional, la Compartida o la Popular. Se encuentra especificada en la Constitución vigente.

- **Soberanía Nacional:** concepto ilustrado definido por Rousseau que dicta que el poder de la nación recae sobre los ciudadanos, los cuales a través del voto delegan su poder en los representantes de las Cortes.

- **Socialismo:** ideología política, económica y social que busca que el Estado controle la producción de bienes y servicios. Distinguimos dos corrientes: el Socialismo Utópico propuesto por Robert Owen y el Socialismo Científico o Marxismo de Karl Marx. Se trata de una ideología presente dentro de la AIT.

- **Sufragio censatario:** sistema de votación en el cual únicamente pueden votar aquellos que cumplan determinadas condiciones económicas, sociales o de formación. Durante la Década Moderada (1845-1854), el sufragio era censatario e inferior al (1%), lo cual causaba que sólo pudieran votar la iglesia, el ejército y grandes contribuyentes.

- **Sufragio Universal Masculino:** sistema de votación recogido en la Constitución en el cual pueden votar todos los hombres sin importar sus condiciones económicas o sociales siempre que superen la mayoría de edad. Se trata de una medida progresista. En el siglo XIX español aparece por primera vez en el Sexenio Democrático (1868-1874) y en la Restauración (1874-1931) aparece en 1890.

- **Turnismo:** sistema de gobierno utilizado en la Restauración (1873-1931) diseñado por Cánovas, basándose en el de Gran Bretaña, que tiene como objetivo alcanzar la estabilidad política. Se basa en cuatro pilares: el rey como cabeza simbólica del ejército (para evitar pronunciamientos), los partidos dinásticos (el liberal y el conservador, los cuales protegían el sistema), el rey como árbitro político (decide cuándo gobierna cada partido) y la Constitución de 1876.